# Generated by Django 4.2 on 2023-11-05 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='value_date',
            field=models.DateField(default=datetime.date(2023, 11, 5)),
        ),
    ]
