# Generated by Django 4.2 on 2023-12-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='currencytimeseriessatellite',
            name='currency_cu_hash_id_3ce7a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='currencytimeseriessatellite',
            name='currency_cu_hash_va_be6dbd_idx',
        ),
    ]
