# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currencyhub_state_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyhub',
            name='is_deleted',
        ),
    ]
