# Generated by Django 4.2 on 2023-11-05 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currencytimeseriessatellite_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='value_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
