# Generated by Django 4.2 on 2023-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currencytimeseriessatellite_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='value_date',
            field=models.DateField(),
        ),
    ]
