# Generated by Django 4.2 on 2023-11-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_currencytimeseriessatellite_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_static_satellites', to='currency.currencyhub'),
        ),
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_time_series_satellites', to='currency.currencyhub'),
        ),
    ]
