# Generated by Django 4.2 on 2023-11-25 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_currencystaticsatellite_hub_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystaticsatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='currencystaticsatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
