# Generated by Django 5.2.9 on 2026-02-03 10:23

import baseclasses.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0026_delete_mockmodel"),
        ("info", "0003_linktesthubatesthubb_testhubvaluedatea_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadRegistryHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("identifier", models.CharField(default="", max_length=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadRegistryHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="info.downloadregistryhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadRegistrySatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("download_name", models.CharField()),
                (
                    "dowload_type",
                    models.CharField(
                        choices=[
                            ("xlsx", "xlsx"),
                            ("csv", "csv"),
                            ("api", "api"),
                            ("pdf", "pdf"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info.downloadregistryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="LinkTestHubATestHubB",
        ),
        migrations.DeleteModel(
            name="TestHubA",
        ),
        migrations.DeleteModel(
            name="TestHubB",
        ),
        migrations.DeleteModel(
            name="TestHubValueDateA",
        ),
        migrations.DeleteModel(
            name="TestHubValueDateB",
        ),
        migrations.DeleteModel(
            name="TestSatA1",
        ),
        migrations.DeleteModel(
            name="TestSatA2",
        ),
        migrations.DeleteModel(
            name="TestSatB1",
        ),
        migrations.DeleteModel(
            name="TestSatB2",
        ),
        migrations.DeleteModel(
            name="TestSatTSB1",
        ),
        migrations.DeleteModel(
            name="TestSatTSB2",
        ),
        migrations.AddIndex(
            model_name="downloadregistryhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="info_downlo_value_d_d92723_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadregistryhubvaluedate",
            index=models.Index(fields=["hub"], name="info_downlo_hub_id_787950_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadregistrysatellite",
            index=models.Index(
                fields=["hash_identifier"], name="info_downlo_hash_id_86f466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadregistrysatellite",
            index=models.Index(
                fields=["hash_value"], name="info_downlo_hash_va_b12f93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadregistrysatellite",
            index=models.Index(
                fields=["hub_entity"], name="info_downlo_hub_ent_39d9c8_idx"
            ),
        ),
    ]
