# Generated by Django 5.2.9 on 2026-02-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_downloadregistryhub_downloadregistryhubvaluedate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadregistrysatellite",
            old_name="dowload_type",
            new_name="download_type",
        ),
    ]
