# Generated by Django 5.2.9 on 2026-02-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_rename_dowload_type_downloadregistrysatellite_download_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadregistrysatellite",
            name="download_type",
            field=models.CharField(
                choices=[
                    ("xlsx", "xlsx"),
                    ("csv", "csv"),
                    ("api", "api"),
                    ("pdf", "pdf"),
                    ("txt", "txt"),
                    ("zip", "zip"),
                ],
                max_length=25,
            ),
        ),
    ]
