# Generated by Django 5.2.9 on 2026-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0008_alter_downloadregistrysatellite_download_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadregistrysatellite",
            name="download_type",
            field=models.CharField(
                choices=[
                    ("xlsx", "xlsx"),
                    ("xls", "xls"),
                    ("csv", "csv"),
                    ("tsv", "tsv"),
                    ("ods", "ods"),
                    ("pdf", "pdf"),
                    ("docx", "docx"),
                    ("doc", "doc"),
                    ("txt", "txt"),
                    ("md", "md"),
                    ("rtf", "rtf"),
                    ("html", "html"),
                    ("json", "json"),
                    ("xml", "xml"),
                    ("yaml", "yaml"),
                    ("yml", "yml"),
                    ("parquet", "parquet"),
                    ("avro", "avro"),
                    ("toml", "toml"),
                    ("zip", "zip"),
                    ("tar", "tar"),
                    ("gz", "gz"),
                    ("tgz", "tgz"),
                    ("7z", "7z"),
                    ("png", "png"),
                    ("jpg", "jpg"),
                    ("jpeg", "jpeg"),
                    ("svg", "svg"),
                    ("mp3", "mp3"),
                    ("mp4", "mp4"),
                    ("api", "api"),
                ],
                max_length=25,
            ),
        ),
    ]
