# Generated by Django 5.0.4 on 2024-05-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_upload', '0002_rename_endpoint_apiuploadregistrystaticsatellite_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apiuploadregistrystaticsatellite',
            name='api_upload__hash_id_be5101_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiuploadregistrystaticsatellite',
            name='api_upload__hash_va_958c8f_idx',
        ),
    ]
