# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_upload", "0004_apiuploadregistryhubvaluedate"),
        (
            "baseclasses",
            "0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apiuploadregistryhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="api_upload__value_d_faa112_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuploadregistryhubvaluedate",
            index=models.Index(fields=["hub"], name="api_upload__hub_id_c1ef90_idx"),
        ),
    ]
