# Generated by Django 5.1.5 on 2025-03-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_upload', '0005_apiuploadregistryhubvaluedate_api_upload__value_d_faa112_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuploadregistrystaticsatellite',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='apiuploadregistryhubvaluedate',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='apiuploadregistryhubvaluedate',
            name='value_date_list',
        ),
        migrations.RemoveField(
            model_name='apiuploadregistrystaticsatellite',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ApiUploadRegistryHub',
        ),
        migrations.DeleteModel(
            name='ApiUploadRegistryHubValueDate',
        ),
        migrations.DeleteModel(
            name='ApiUploadRegistryStaticSatellite',
        ),
    ]
