# Generated by Django 4.2 on 2024-02-04 09:51

import asset.managers.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('identifier', models.CharField(default='', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkAssetCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assethub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currencyhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTimeSeriesSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('value_date', models.DateField()),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_time_series_satellite', to='asset.assethub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('ETF', 'Etf'), ('STOCK', 'Stock'), ('BOND', 'Bond'), ('REAL_ESTATE', 'Real Estate')], max_length=100)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_static_satellite', to='asset.assethub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetLiquidSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('asset_isin', models.CharField(max_length=12, validators=[asset.managers.validators.montrek_isin_validator])),
                ('asset_wkn', models.CharField(max_length=6, validators=[asset.managers.validators.montrek_wkn_validator])),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_liquid_satellite', to='asset.assethub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assethub',
            name='link_asset_currency',
            field=models.ManyToManyField(related_name='link_currency_asset', through='asset.LinkAssetCurrency', to='currency.currencyhub'),
        ),
        migrations.AddIndex(
            model_name='assetstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='asset_asset_hash_id_694ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstaticsatellite',
            index=models.Index(fields=['hash_value'], name='asset_asset_hash_va_8ffcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetliquidsatellite',
            index=models.Index(fields=['hash_identifier'], name='asset_asset_hash_id_9f954a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetliquidsatellite',
            index=models.Index(fields=['hash_value'], name='asset_asset_hash_va_c3155d_idx'),
        ),
    ]
