# Generated by Django 4.2 on 2023-10-24 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTimeSeriesSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_satellites', to='asset.assethub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('name', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=100)),
                ('wkn', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_satellites', to='asset.assethub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assettimeseriessatellite',
            index=models.Index(fields=['hash_identifier'], name='asset_asset_hash_id_1823fe_idx'),
        ),
        migrations.AddIndex(
            model_name='assettimeseriessatellite',
            index=models.Index(fields=['hash_value'], name='asset_asset_hash_va_459011_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='asset_asset_hash_id_694ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstaticsatellite',
            index=models.Index(fields=['hash_value'], name='asset_asset_hash_va_8ffcdc_idx'),
        ),
    ]
