# Generated by Django 4.2 on 2023-10-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetstaticsatellite',
            old_name='isin',
            new_name='asset_isin',
        ),
        migrations.RenameField(
            model_name='assetstaticsatellite',
            old_name='name',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='assetstaticsatellite',
            old_name='wkn',
            new_name='asset_wkn',
        ),
    ]
