# Generated by Django 4.2 on 2023-12-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currencytimeseriessatellite_currency_cu_hash_id_3ce7a7_idx_and_more'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethub',
            name='link_asset_currency',
            field=models.ManyToManyField(related_name='link_currency_asset', to='currency.currencyhub'),
        ),
    ]
