# Generated by Django 4.2 on 2023-10-24 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_rename_isin_assetstaticsatellite_asset_isin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstaticsatellite',
            name='asset_isin',
        ),
        migrations.RemoveField(
            model_name='assetstaticsatellite',
            name='asset_wkn',
        ),
        migrations.CreateModel(
            name='AssetLiquidSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('asset_isin', models.CharField(max_length=100)),
                ('asset_wkn', models.CharField(max_length=100)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquid_satellites', to='asset.assethub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assetliquidsatellite',
            index=models.Index(fields=['hash_identifier'], name='asset_asset_hash_id_9f954a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetliquidsatellite',
            index=models.Index(fields=['hash_value'], name='asset_asset_hash_va_c3155d_idx'),
        ),
    ]
