# Generated by Django 4.2 on 2023-10-24 12:54

import asset.managers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_remove_assetstaticsatellite_asset_isin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetliquidsatellite',
            name='asset_isin',
            field=models.CharField(max_length=12, validators=[asset.managers.validators.montrek_isin_validator]),
        ),
        migrations.AlterField(
            model_name='assetliquidsatellite',
            name='asset_wkn',
            field=models.CharField(max_length=6, validators=[asset.managers.validators.montrek_wkn_validator]),
        ),
    ]
