# Generated by Django 4.2 on 2024-01-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_assethub_state_date_end_assethub_state_date_start'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assettimeseriessatellite',
            name='asset_asset_hash_id_1823fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='assettimeseriessatellite',
            name='asset_asset_hash_va_459011_idx',
        ),
    ]
