# Generated by Django 4.2 on 2023-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_assetliquidsatellite_asset_isin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='asset_name',
            field=models.CharField(choices=[('ETF', 'Etf'), ('STOCK', 'Stock'), ('BOND', 'Bond'), ('REAL_ESTATE', 'Real Estate')], max_length=20),
        ),
    ]
