# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_remove_assettimeseriessatellite_asset_asset_hash_id_1823fe_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethub',
            name='is_deleted',
        ),
    ]
