# Generated by Django 4.2 on 2023-10-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_assetstaticsatellite_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='asset_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='asset_type',
            field=models.CharField(choices=[('ETF', 'Etf'), ('STOCK', 'Stock'), ('BOND', 'Bond'), ('REAL_ESTATE', 'Real Estate')], max_length=100),
        ),
    ]
