# Generated by Django 4.2 on 2024-02-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_remove_assethub_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettimeseriessatellite',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
