# Generated by Django 4.2 on 2023-10-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_assetstaticsatellite_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetliquidsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_liquid_satellite', to='asset.assethub'),
        ),
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='asset_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_static_satellite', to='asset.assethub'),
        ),
        migrations.AlterField(
            model_name='assettimeseriessatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_time_series_satellite', to='asset.assethub'),
        ),
    ]
