# Generated by Django 4.2 on 2023-10-27 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_assetliquidsatellite_hub_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettimeseriessatellite',
            name='value_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
