# Generated by Django 4.2 on 2023-11-05 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_assettimeseriessatellite_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetliquidsatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assetliquidsatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assetstaticsatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assettimeseriessatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assettimeseriessatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
