# Generated by Django 4.2 on 2023-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_currencystaticsatellite_hub_entity_and_more'),
        ('asset', '0009_alter_assetliquidsatellite_state_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethub',
            name='link_asset_currency',
            field=models.ManyToManyField(related_name='link_asset_currency', to='currency.currencyhub'),
        ),
    ]
