from dataclasses import dataclass, field

@dataclass
class ReportingColors:
    WHITE = '#FFFFFF'
    BLUE = '#004767'
    LIGHT_BLUE = '#E6F2F8'
    DARK_BLUE = '#002F6C'
    RED = '#BE0D3E'
    DARKER_RED = '#821621'
    MEDIUM_BLUE = '#2B6D8B'
    SOFT_ROSE = '#D3A9A1'
    SOFT_SKY = '#6B93B0'
    LIGHT_ROSE = '#FBE8E8'
    LIGHT_SKY = '#B1CFE2'
    BRIGHTER_RED = '#E64C4C'
    DARK_GREEN = '#1B5E20'
    DARK_ORANGE = '#FF6F00'
    YELLOW = '#FDD835'
    BROWN = '#6D4C41'
    PURPLE = '#7E57C2'
    TEAL = '#26A69A'
    BRIGHTER_RED = '#D32F2F'
    BRIGHTER_BLUE = '#0277BD'
    BRIGHTER_GREEN = '#388E3C'
    BRIGHTER_ORANGE = '#FFA000'
    BRIGHTER_YELLOW = '#FBC02D'
    DARKER_BROWN = '#5D4037'

    COLOR_PALETTE = [
        RED, BLUE, LIGHT_BLUE, DARK_GREEN, DARK_ORANGE, YELLOW, BROWN,
        PURPLE, TEAL, BRIGHTER_RED, BRIGHTER_BLUE, BRIGHTER_GREEN, BRIGHTER_ORANGE,
        BRIGHTER_YELLOW, DARKER_BROWN
    ]

    COLOR_PALETTE_GRADIENT = [RED, BLUE, LIGHT_BLUE, DARKER_RED, MEDIUM_BLUE, SOFT_ROSE, SOFT_SKY, LIGHT_ROSE, LIGHT_SKY, BRIGHTER_RED]
