"""
Django settings for montrek project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import Config, RepositoryEnv
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
config = Config(RepositoryEnv(BASE_DIR / "../.env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2@8w*43%w2=36x1y3#v8mlll#!3kw9)jnn&^i&xw-o8^br_od-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

PROJECT_NAME = config("PROJECT_NAME", default="default")
DEPLOY_HOST = config("DEPLOY_HOST", default="127.0.0.1")
DEPLOY_PORT = config("DEPLOY_PORT", default="1339")
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    f"montrek.{PROJECT_NAME}",
    f"{DEPLOY_HOST}:{DEPLOY_PORT}",
    DEPLOY_HOST,
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "debug_toolbar",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "rest_framework",
]


def get_montrek_extension_apps(base_dir, app_path=""):
    """
    Recursively find Montrek extension apps by identifying directories
    containing an 'apps.py' file.

    Args:
        base_dir (Path): The base directory to search.
        app_path (str): The relative app path for current recursion level.

    Returns:
        list: A list of fully qualified app names.
    """
    full_path = base_dir / app_path.replace(".", os.sep)
    montrek_apps = []

    if not full_path.is_dir():
        return montrek_apps

    # Check if the current directory contains 'apps.py'
    if "apps.py" in os.listdir(full_path):
        montrek_apps.append(app_path)
    else:
        # Recurse into subdirectories
        for subdir in os.listdir(full_path):
            subdir_path = full_path / subdir
            if subdir_path.is_dir():
                sub_app_path = f"{app_path}.{subdir}" if app_path else subdir
                montrek_apps.extend(get_montrek_extension_apps(base_dir, sub_app_path))

    return montrek_apps


def get_montrek_extension_apps_list():
    """
    Get the list of Montrek extension apps from the configured installed apps.

    Returns:
        list: Fully qualified Montrek extension apps.
    """
    base_dir = Path(BASE_DIR)
    return get_montrek_extension_apps(base_dir, "")


MONTREK_EXTENSION_APPS = get_montrek_extension_apps_list()

INSTALLED_APPS = DJANGO_APPS + MONTREK_EXTENSION_APPS

DJANGO_MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

MONTREK_MIDDLEWARE = [
    "middleware.LoginRequiredMiddleware",
    "middleware.PermissionErrorMiddleware",
    "middleware.MontrekErrorMiddleware",
]

MIDDLEWARE = DJANGO_MIDDLEWARE + MONTREK_MIDDLEWARE

ROOT_URLCONF = "montrek.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["baseclasses/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TEMPLATES[0]["DIRS"] += [
    app.replace(".", "/") + "/templates" for app in MONTREK_EXTENSION_APPS
]

WSGI_APPLICATION = "montrek.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASE_ENGINE_MAP = {
    "mariadb": "django.db.backends.mysql",
    "postgres": "django.db.backends.postgresql",
    "cloudsqlproxy": "django.db.backends.postgresql",
}

DATABASES = {
    "default": {
        "ENGINE": DATABASE_ENGINE_MAP[config("DB_ENGINE", default="mariadb")],
        "NAME": config("DB_NAME", default="montrek_db"),
        "USER": config("DB_USER", default="root"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config(
            "DB_HOST", default="localhost"
        ),  # in docker setup: docker-compose service name (db)
        "PORT": config(
            "DB_PORT", default=3306, cast=int
        ),  # in docker setup: internal docker container port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "user.MontrekUser"

LOGIN_URL = reverse_lazy("login")
LOGIN_REDIRECT_URL = reverse_lazy("home")

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "baseclasses/static")

MEDIA_URL = "/uploads/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CSRF_TRUSTED_ORIGINS = [
    f"http://{host}:{DEPLOY_PORT}"
    for host in ["localhost", "127.0.0.1", DEPLOY_HOST, f"montrek.{PROJECT_NAME}"]
]
CSRF_TRUSTED_ORIGINS += [
    f"https://montrek.{PROJECT_NAME}:{DEPLOY_PORT}",
    f"https://{DEPLOY_HOST}:{DEPLOY_PORT}",
]

EMAIL_HOST = config("EMAIL_HOST", default=None)
if not EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
    EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_TEMPLATE = config("EMAIL_TEMPLATE", "mail_templates/montrek_mail_template.html")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="")

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379")
CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=True, cast=bool)
# number of messages the worker can prefetch from the broker
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# time to wait for the worker to acknowledge the task before the message is re-queued
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600 * 10,  # 10 hours
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": config("LOG_LEVEL", default="WARNING"),
        },
    },
    "root": {
        "handlers": ["console"],
        "level": config("LOG_LEVEL", default="WARNING"),
    },
}
# Testing
TEST_RUNNER = "montrek.testing.test_runner.MontrekTestRunner"

MONTREK_GITHUB_TOKEN = config("MONTREK_GITHUB_TOKEN", default="")

LOGIN_EXEMPT_PATHS = ["/user", "/admin", "/api"]

INTERNAL_IPS = [
    "127.0.0.1",
]

# TABLE Generation
SEND_TABLE_BY_MAIL_LIMIT = config("SEND_TABLE_BY_MAIL_LIMIT", default=10000, cast=int)

ADMIN_MAILING_LIST = config("ADMIN_MAILING_LIST", default="")
