# Generated by Django 4.2 on 2023-11-26 17:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_institution', '0001_initial'),
        ('file_upload', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('link_account_credit_institution', models.ManyToManyField(related_name='link_credit_institution_account', to='credit_institution.creditinstitutionhub')),
                ('link_account_file_upload_registry', models.ManyToManyField(related_name='link_file_upload_registry_account', to='file_upload.fileuploadregistryhub')),
                ('link_account_transaction', models.ManyToManyField(related_name='link_transaction_account', to='transaction.transactionhub')),
                ('link_account_transaction_category_map', models.ManyToManyField(related_name='link_transaction_category_map_account', to='transaction.transactioncategorymaphub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccountStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('bank_account_iban', models.CharField(default='XX00000000000000000000', max_length=34, validators=[django.core.validators.RegexValidator(message='Invalid IBAN format.', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')])),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounthub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccountPropertySatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounthub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('account_type', models.CharField(choices=[('Other', 'Other'), ('BankAccount', 'Bank Account'), ('Cash', 'Cash'), ('Depot', 'Depot'), ('RealEstate', 'Real Estate')], default='Other', max_length=15)),
                ('account_name', models.CharField(max_length=50)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounthub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='bankaccountstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='account_ban_hash_id_c18404_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountstaticsatellite',
            index=models.Index(fields=['hash_value'], name='account_ban_hash_va_a3a3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountpropertysatellite',
            index=models.Index(fields=['hash_identifier'], name='account_ban_hash_id_e14fef_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountpropertysatellite',
            index=models.Index(fields=['hash_value'], name='account_ban_hash_va_a2c051_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='account_acc_hash_id_3733d3_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstaticsatellite',
            index=models.Index(fields=['hash_value'], name='account_acc_hash_va_49d938_idx'),
        ),
    ]
