# Generated by Django 4.2 on 2023-06-22 10:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccountStaticSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bank_account_iban",
                    models.CharField(
                        default="XX00000000000000000000",
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid IBAN format.",
                                regex="^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$",
                            )
                        ],
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.accounthub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccountPropertySatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.accounthub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountStaticSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("BankAccount", "Bank Account"),
                            ("Cash", "Cash"),
                            ("Depot", "Depot"),
                            ("RealEstate", "Real Estate"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("account_name", models.CharField(max_length=50)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.accounthub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
