# Generated by Django 4.2 on 2024-02-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_upload", "0001_initial"),
        ("credit_institution", "0001_initial"),
        ("account", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkaccounttransactioncategorymap",
            name="hub_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transactioncategorymaphub",
            ),
        ),
        migrations.AddField(
            model_name="linkaccounttransaction",
            name="hub_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.accounthub"
            ),
        ),
        migrations.AddField(
            model_name="linkaccounttransaction",
            name="hub_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transactionhub",
            ),
        ),
        migrations.AddField(
            model_name="linkaccountfileuploadregistry",
            name="hub_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.accounthub"
            ),
        ),
        migrations.AddField(
            model_name="linkaccountfileuploadregistry",
            name="hub_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="file_upload.fileuploadregistryhub",
            ),
        ),
        migrations.AddField(
            model_name="linkaccountcreditinstitution",
            name="hub_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.accounthub"
            ),
        ),
        migrations.AddField(
            model_name="linkaccountcreditinstitution",
            name="hub_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_institution.creditinstitutionhub",
            ),
        ),
        migrations.AddField(
            model_name="bankaccountstaticsatellite",
            name="hub_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.accounthub"
            ),
        ),
        migrations.AddField(
            model_name="bankaccountpropertysatellite",
            name="hub_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.accounthub"
            ),
        ),
        migrations.AddField(
            model_name="accountstaticsatellite",
            name="hub_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.accounthub"
            ),
        ),
        migrations.AddField(
            model_name="accounthub",
            name="link_account_credit_institution",
            field=models.ManyToManyField(
                related_name="link_credit_institution_account",
                through="account.LinkAccountCreditInstitution",
                to="credit_institution.creditinstitutionhub",
            ),
        ),
        migrations.AddField(
            model_name="accounthub",
            name="link_account_file_upload_registry",
            field=models.ManyToManyField(
                related_name="link_file_upload_registry_account",
                through="account.LinkAccountFileUploadRegistry",
                to="file_upload.fileuploadregistryhub",
            ),
        ),
        migrations.AddField(
            model_name="accounthub",
            name="link_account_transaction",
            field=models.ManyToManyField(
                related_name="link_transaction_account",
                through="account.LinkAccountTransaction",
                to="transaction.transactionhub",
            ),
        ),
        migrations.AddField(
            model_name="accounthub",
            name="link_account_transaction_category_map",
            field=models.ManyToManyField(
                related_name="link_transaction_category_map_account",
                through="account.LinkAccountTransactionCategoryMap",
                to="transaction.transactioncategorymaphub",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccountstaticsatellite",
            index=models.Index(
                fields=["hash_identifier"], name="account_ban_hash_id_c18404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccountstaticsatellite",
            index=models.Index(
                fields=["hash_value"], name="account_ban_hash_va_a3a3e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccountpropertysatellite",
            index=models.Index(
                fields=["hash_identifier"], name="account_ban_hash_id_e14fef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccountpropertysatellite",
            index=models.Index(
                fields=["hash_value"], name="account_ban_hash_va_a2c051_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountstaticsatellite",
            index=models.Index(
                fields=["hash_identifier"], name="account_acc_hash_id_3733d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountstaticsatellite",
            index=models.Index(
                fields=["hash_value"], name="account_acc_hash_va_49d938_idx"
            ),
        ),
    ]
