# Generated by Django 4.2 on 2023-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthub',
            name='link_account_transaction',
            field=models.ManyToManyField(related_name='link_transaction_account', to='transaction.transactionhub'),
        ),
        migrations.AddField(
            model_name='accounthub',
            name='link_account_transaction_category_map',
            field=models.ManyToManyField(related_name='link_transaction_category_map_account', to='transaction.transactioncategorymaphub'),
        ),
        migrations.AddIndex(
            model_name='bankaccountstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='account_ban_hash_id_c18404_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountstaticsatellite',
            index=models.Index(fields=['hash_value'], name='account_ban_hash_va_a3a3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountpropertysatellite',
            index=models.Index(fields=['hash_identifier'], name='account_ban_hash_id_e14fef_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountpropertysatellite',
            index=models.Index(fields=['hash_value'], name='account_ban_hash_va_a2c051_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='account_acc_hash_id_3733d3_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstaticsatellite',
            index=models.Index(fields=['hash_value'], name='account_acc_hash_va_49d938_idx'),
        ),
    ]
