# Generated by Django 4.2 on 2023-04-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthub',
            old_name='name',
            new_name='identifier',
        ),
    ]
