# Generated by Django 4.2 on 2023-08-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_institution", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthub",
            name="link_account_credit_institution",
            field=models.ManyToManyField(
                related_name="link_credit_institution_account",
                to="credit_institution.creditinstitutionhub",
            ),
        ),
    ]
