# Generated by Django 4.2 on 2023-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_linkaccountcreditinstitution_state_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkaccountcreditinstitution',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linkaccountcreditinstitution',
            old_name='out_hub',
            new_name='hub_out',
        ),
        migrations.RenameField(
            model_name='linkaccountfileuploadregistry',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linkaccountfileuploadregistry',
            old_name='out_hub',
            new_name='hub_out',
        ),
        migrations.RenameField(
            model_name='linkaccounttransaction',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linkaccounttransaction',
            old_name='out_hub',
            new_name='hub_out',
        ),
        migrations.RenameField(
            model_name='linkaccounttransactioncategorymap',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linkaccounttransactioncategorymap',
            old_name='out_hub',
            new_name='hub_out',
        ),
    ]
