# Generated by Django 4.2 on 2023-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction",
            "0010_transactionhub_link_transaction_transaction_category_and_more",
        ),
        ("account", "0002_accounthub_link_account_credit_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthub",
            name="link_account_transaction",
            field=models.ManyToManyField(
                related_name="link_transaction_account", to="transaction.transactionhub"
            ),
        ),
    ]
