# Generated by Django 4.2 on 2023-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0001_initial"),
        ("account", "0003_accounthub_link_account_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthub",
            name="link_account_file_upload_registry",
            field=models.ManyToManyField(
                related_name="link_file_upload_registry_account",
                to="file_upload.fileuploadregistryhub",
            ),
        ),
    ]
