# Generated by Django 4.2 on 2023-04-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountstaticsatellite'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.accounthub'),
            preserve_default=False,
        ),
    ]
