# Generated by Django 4.2 on 2023-12-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_in_hub_linkaccountcreditinstitution_hub_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthub',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='accounthub',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
