# Generated by Django 4.2 on 2023-08-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0011_remove_transactiontransactiontypelink_from_hub_and_more"),
        ("account", "0004_accounthub_link_account_file_upload_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthub",
            name="link_account_transaction_category_map",
            field=models.ManyToManyField(
                related_name="link_transaction_category_map_account",
                to="transaction.transactioncategorymaphub",
            ),
        ),
    ]
