# Generated by Django 4.2 on 2023-04-16 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountstaticsatellite_hub_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstaticsatellite',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='accountstaticsatellite',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 19, 44, 58, 67769, tzinfo=datetime.timezone.utc)),
        ),
    ]
