# Generated by Django 4.2 on 2023-05-07 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_accountstaticsatellite_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstaticsatellite',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
