# Generated by Django 4.2 on 2023-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accounthub_link_account_transaction_category_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
