# Generated by Django 4.2 on 2024-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotsatelitte',
            name='hub_entity',
        ),
        migrations.DeleteModel(
            name='DepotHub',
        ),
        migrations.DeleteModel(
            name='DepotSatelitte',
        ),
    ]
