# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_depothub_state_date_end_depothub_state_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depothub',
            name='is_deleted',
        ),
    ]
