# Generated by Django 4.2 on 2023-07-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_upload", "0001_initial"),
        (
            "transaction",
            "0004_transactionhub_created_at_transactionhub_updated_at_and_more",
        ),
        ("credit_institution", "0005_creditinstitutionhub_created_at_and_more"),
        ("account", "0004_accounthub_created_at_accounthub_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUploadRegistryTransactionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload_registry_transaction_link_from_hub",
                        to="file_upload.fileuploadregistryhub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload_registry_transaction_link_to_hub",
                        to="transaction.transactionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileUploadRegistryFileUploadFileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload_registry_file_upload_file_link_from_hub",
                        to="file_upload.fileuploadregistryhub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload_registry_file_upload_file_link_to_hub",
                        to="file_upload.fileuploadfilehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountTransactionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transaction_link_from_hub",
                        to="account.accounthub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transaction_to_hub",
                        to="transaction.transactionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountFileUploadRegistryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_file_upload_registry_link_from_hub",
                        to="account.accounthub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_file_upload_registry_link_to_hub",
                        to="file_upload.fileuploadregistryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountCreditInstitutionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_credit_institution_link_from_hub",
                        to="account.accounthub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_credit_institution_link_to_hub",
                        to="credit_institution.creditinstitutionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
