# Generated by Django 4.2 on 2023-07-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transaction", "0003_remove_transactionhub_created_at_and_more"),
        ("credit_institution", "0004_remove_creditinstitutionhub_created_at_and_more"),
        ("account", "0003_remove_accounthub_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTransactionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transaction_link_from_hub",
                        to="account.accounthub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transaction_to_hub",
                        to="transaction.transactionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountCreditInstitutionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_credit_institution_link_from_hub",
                        to="account.accounthub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_credit_institution_link_to_hub",
                        to="credit_institution.creditinstitutionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
