# Generated by Django 4.2 on 2023-05-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_accountstaticsatellite_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_hub', to='account.accounthub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
