# Generated by Django 4.2 on 2023-05-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('link_tables', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransactionlink',
            name='to_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_hub', to='transaction.transactionhub'),
        ),
    ]
