# Generated by Django 4.2 on 2023-07-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0007_transactioncategorymaphub_and_more"),
        ("account", "0001_initial"),
        ("link_tables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTransactionCategoryMapLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transaction_category_map_link_from_hub",
                        to="account.accounthub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transaction_category_map_link_to_hub",
                        to="transaction.transactioncategorymaphub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
