from django.urls import path
from transaction import views

urlpatterns = [
    path(
        "create/<int:account_id>",
        views.TransactionCreateFromAccountView.as_view(),
        name="transaction_create_from_account",
    ),
    path(
        "<int:pk>/details/",
        views.TransactionDetailView.as_view(),
        name="transaction_details",
    ),
    path(
        "<int:pk>/update/",
        views.TransactionUpdateView.as_view(),
        name="transaction_update",
    ),
    path(
        "add_transaction_category/<int:account_id>/cp/<str:counterparty>",
        views.TransactionCategoryMapCreateView.as_view(),
        name="transaction_category_add_form_with_counterparty",
    ),
    path(
        "add_transaction_category/<int:account_id>/iban/<str:iban>",
        views.TransactionCategoryMapCreateView.as_view(),
        name="transaction_category_add_form_with_iban",
    ),
    path(
        "category/create/<int:account_id>",
        views.TransactionCategoryMapCreateView.as_view(),
        name="transaction_category_map_create",
    ),
    path(
        "category/<int:pk>/update/<int:account_id>",
        views.TransactionCategoryMapUpdateView.as_view(),
        name="transaction_category_map_update",
    ),
    path(
        "category/<int:pk>/details/<int:account_id>",
        views.TransactionCategoryMapDetailView.as_view(),
        name="transaction_category_map_details",
    ),
    path(
        "delete_transcation_category_map/<int:account_id>/<int:pk>",
        views.TransactionCategoryMapDeleteView.as_view(),
        name="transaction_category_map_delete",
    ),
]
