# Generated by Django 5.0.4 on 2024-04-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_upload", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apiuploadregistrystaticsatellite",
            old_name="endpoint",
            new_name="url",
        ),
    ]
