# Generated by Django 5.0.4 on 2024-11-15 13:49

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_upload",
            "0003_remove_apiuploadregistrystaticsatellite_api_upload__hash_id_be5101_idx_and_more",
        ),
        ("baseclasses", "0005_alter_testhubvaluedate_hub"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUploadRegistryHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="api_upload.apiuploadregistryhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
