from django.urls import path
from montrek_example import views


urlpatterns = [
    path(
        "",
        views.MontrekExampleReport.as_view(),
        name="montrek_example_report",
    ),
    path(
        "a/create",
        views.MontrekExampleACreate.as_view(),
        name="montrek_example_a_create",
    ),
    path("a/list", views.MontrekExampleAList.as_view(), name="montrek_example_a_list"),
    path(
        "b/create",
        views.MontrekExampleBCreate.as_view(),
        name="montrek_example_b_create",
    ),
    path(
        "b/<int:pk>/update",
        views.MontrekExampleBUpdate.as_view(),
        name="montrek_example_b_update",
    ),
    path("b/list", views.MontrekExampleBList.as_view(), name="montrek_example_b_list"),
    path(
        "a/<int:pk>/update",
        views.MontrekExampleAUpdate.as_view(),
        name="montrek_example_a_update",
    ),
    path(
        "a/<int:pk>/details",
        views.MontrekExampleADetails.as_view(),
        name="montrek_example_a_details",
    ),
    path(
        "a/<int:pk>/delete",
        views.MontrekExampleADelete.as_view(),
        name="montrek_example_a_delete",
    ),
    path(
        "a/<int:pk>/history",
        views.MontrekExampleAHistory.as_view(),
        name="montrek_example_a_history",
    ),
    path(
        "c/list",
        views.MontrekExampleCList.as_view(),
        name="montrek_example_c_list",
    ),
    path(
        "c/create",
        views.MontrekExampleCCreate.as_view(),
        name="montrek_example_c_create",
    ),
    path(
        "d/list",
        views.MontrekExampleDList.as_view(),
        name="montrek_example_d_list",
    ),
    path(
        "d/create",
        views.MontrekExampleDCreate.as_view(),
        name="montrek_example_d_create",
    ),
    path(
        "a1_field_map/list",
        views.MontrekExampleA1FieldMapListView.as_view(),
        name="montrek_example_a1_field_map_list",
    ),
    path(
        "a1_field_map/create",
        views.MontrekExampleA1FieldMapCreateView.as_view(),
        name="montrek_example_a1_field_map_create",
    ),
    path(
        "a1_field_map/update/<int:pk>",
        views.MontrekExampleA1FieldMapUpdateView.as_view(),
        name="montrek_example_a1_field_map_update",
    ),
    path(
        "a1_field_map/delete/<int:pk>",
        views.MontrekExampleA1FieldMapDeleteView.as_view(),
        name="montrek_example_a1_field_map_delete",
    ),
    path(
        "a1_upload_file",
        views.MontrekExampleA1UploadFileView.as_view(),
        name="a1_upload_file",
    ),
    path(
        "a1_view_uploads",
        views.MontrekExampleA1UploadView.as_view(),
        name="a1_view_uploads",
    ),
    path(
        "a1_download_file/<int:pk>",
        views.MontrekExampleA1DownloadFileView.as_view(),
        name="a1_download_file",
    ),
    path(
        "a1_download_file/<int:pk>/log",
        views.MontrekExampleA1DownloadLogFileView.as_view(),
        name="a1_download_log_file",
    ),
    path(
        "hub_a_view_api_uploads",
        views.MontrekExampleHubAApiUploadView.as_view(),
        name="hub_a_view_api_uploads",
    ),
    path("do_a2_upload", views.do_a2_upload, name="do_a2_upload"),
    path(
        "a1_file_upload_history/<int:pk>",
        views.MontrekExampleA1UploadHistoryView.as_view(),
        name="a1_file_upload_history",
    ),
    path(
        "run_example_parallel_task",
        views.do_run_example_parallel_task,
        name="run_example_parallel_task",
    ),
    path(
        "run_example_sequential_task",
        views.do_run_example_sequential_task,
        name="run_example_sequential_task",
    ),
    path("hub_a/api", views.HubARestApiView.as_view(), name="hub_a_rest_api"),
]
