# Generated by Django 4.2 on 2024-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailsatellite_mail_state_mailstatesatellite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailstatesatellite',
            name='mail_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
