# Generated by Django 5.0.4 on 2024-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailstatesatellite_mail_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailsatellite",
            name="mail_attachments",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
