# Generated by Django 5.0.4 on 2024-11-14 15:06

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0005_alter_testhubvaluedate_hub"),
        ("mailing", "0003_mailstatesatellite_mail_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="mailing.mailhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
