# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more",
        ),
        ("mailing", "0004_mailhubvaluedate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mailhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="mailing_mai_value_d_730ace_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailhubvaluedate",
            index=models.Index(fields=["hub"], name="mailing_mai_hub_id_c244ef_idx"),
        ),
        migrations.AddIndex(
            model_name="mailstatesatellite",
            index=models.Index(
                fields=["hub_entity"], name="mailing_mai_hub_ent_facc3b_idx"
            ),
        ),
    ]
