# Generated by Django 5.0.4 on 2025-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailhubvaluedate_mailing_mai_value_d_730ace_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsatellite',
            name='mail_attachments',
            field=models.TextField(default=''),
        ),
    ]
