# Generated by Django 5.0.4 on 2025-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mailsatellite_mail_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsatellite',
            name='mail_attachments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
