# Generated by Django 5.1.5 on 2025-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailsatellite_mail_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsatellite',
            name='mail_bcc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
