# Generated by Django 5.1.5 on 2025-03-24 18:59

import baseclasses.fields
import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseclasses', '0008_testmontrektimeseriessatellite'),
        ('file_upload', '0016_fieldmaphubvaluedate_file_upload_value_d_063842_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubAApiUploadRegistryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubAApiUploadRegistryStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('import_message', models.TextField(default='')),
                ('import_url', models.URLField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubaapiuploadregistryhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubAFileUploadRegistryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubAFileUploadRegistryStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'Csv'), ('json', 'Json'), ('xml', 'Xml'), ('xlsx', 'Xlsx'), ('xls', 'Xls'), ('txt', 'Txt'), ('none', 'None')], default='none', max_length=5)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_message', models.TextField(default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.hubc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.hubd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.hube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkHubAApiUploadRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubaapiuploadregistryhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='huba',
            name='link_hub_a_api_upload_registry',
            field=models.ManyToManyField(related_name='link_api_upload_registry_hub_a', through='montrek_example.LinkHubAApiUploadRegistry', to='montrek_example.hubaapiuploadregistryhub'),
        ),
        migrations.CreateModel(
            name='LinkHubAFileUploadRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='huba',
            name='link_hub_a_file_upload_registry',
            field=models.ManyToManyField(related_name='link_file_upload_registry_hub_a', through='montrek_example.LinkHubAFileUploadRegistry', to='montrek_example.hubafileuploadregistryhub'),
        ),
        migrations.CreateModel(
            name='LinkHubAFileUploadRegistryFileLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubafileuploadregistryhub',
            name='link_file_upload_registry_file_log_file',
            field=models.ManyToManyField(related_name='link_file_log_file_hub_a_file_upload_registry', through='montrek_example.LinkHubAFileUploadRegistryFileLogFile', to='file_upload.fileuploadfilehub'),
        ),
        migrations.CreateModel(
            name='LinkHubAFileUploadRegistryFileUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubafileuploadregistryhub',
            name='link_file_upload_registry_file_upload_file',
            field=models.ManyToManyField(related_name='link_file_upload_file_hub_a_file_upload_registry', through='montrek_example.LinkHubAFileUploadRegistryFileUploadFile', to='file_upload.fileuploadfilehub'),
        ),
        migrations.CreateModel(
            name='LinkHubAHubB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='huba',
            name='link_hub_a_hub_b',
            field=models.ManyToManyField(related_name='link_hub_b_hub_a', through='montrek_example.LinkHubAHubB', to='montrek_example.hubb'),
        ),
        migrations.CreateModel(
            name='LinkHubAHubC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='huba',
            name='link_hub_a_hub_c',
            field=models.ManyToManyField(related_name='link_hub_c_hub_a', through='montrek_example.LinkHubAHubC', to='montrek_example.hubc'),
        ),
        migrations.CreateModel(
            name='LinkHubBHubD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubb',
            name='link_hub_b_hub_d',
            field=models.ManyToManyField(related_name='link_hub_d_hub_b', through='montrek_example.LinkHubBHubD', to='montrek_example.hubd'),
        ),
        migrations.CreateModel(
            name='LinkHubCHubD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubc',
            name='link_hub_c_hub_d',
            field=models.ManyToManyField(related_name='link_hub_d_hub_c', through='montrek_example.LinkHubCHubD', to='montrek_example.hubd'),
        ),
        migrations.CreateModel(
            name='SatA1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_a1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_a1_int', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatA1FieldMapHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatA1FieldMapHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.sata1fieldmaphub')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatA1FieldMapStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('source_field', models.CharField(max_length=255)),
                ('database_field', models.CharField(max_length=255)),
                ('step', models.IntegerField(default=1)),
                ('function_name', models.CharField(default='no_change', max_length=255)),
                ('function_parameters', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.sata1fieldmaphub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_a2_str', models.CharField(blank=True, default='DEFAULT', max_length=50, null=True)),
                ('field_a2_float', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatA3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_a3_str', models.CharField(blank=True, default='DEFAULT', max_length=50, null=True)),
                ('field_a3_json', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatB1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('alert_level', models.CharField(choices=[('error', 'error'), ('warning', 'warning'), ('ok', 'ok')], default='ok', max_length=10)),
                ('alert_message', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_b1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_b1_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatB2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_b2_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_b2_choice', models.CharField(choices=[('CHOICE1', 'Choice1'), ('CHOICE2', 'Choice2'), ('CHOICE3', 'Choice3')], default='CHOICE1', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatC1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_c1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_c1_bool', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatD1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_d1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_d1_int', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatE1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_e1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_e1_float', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatE2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('field_e2_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_e2_int', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatTSC2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('field_tsc2_float', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_value_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.chubvaluedate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatTSC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('field_tsc3_int', models.IntegerField(blank=True, null=True)),
                ('field_tsc3_str', models.CharField(blank=True, max_length=50, null=True)),
                ('field_tsc3_int_times_two', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('field_tsc3_int'), '*', models.Value(2)), output_field=models.IntegerField())),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_value_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.chubvaluedate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatTSC4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('field_tsc4_int', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_value_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.chubvaluedate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatTSD2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('field_tsd2_float', models.FloatField(null=True)),
                ('field_tsd2_int', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_value_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.dhubvaluedate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.huba')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['value_date_list'], name='montrek_exa_value_d_7d85d9_idx'), models.Index(fields=['hub'], name='montrek_exa_hub_id_928aa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HubAApiUploadRegistryHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.hubaapiuploadregistryhub')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['value_date_list'], name='montrek_exa_value_d_d07c89_idx'), models.Index(fields=['hub'], name='montrek_exa_hub_id_d40b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HubAFileUploadRegistryHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.hubafileuploadregistryhub')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['value_date_list'], name='montrek_exa_value_d_23fc7a_idx'), models.Index(fields=['hub'], name='montrek_exa_hub_id_35bb87_idx')],
            },
        ),
        migrations.CreateModel(
            name='BHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='montrek_example.hubb')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['value_date_list'], name='montrek_exa_value_d_23ba80_idx'), models.Index(fields=['hub'], name='montrek_exa_hub_id_c4e75c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chubvaluedate',
            index=models.Index(fields=['value_date_list'], name='montrek_exa_value_d_383509_idx'),
        ),
        migrations.AddIndex(
            model_name='chubvaluedate',
            index=models.Index(fields=['hub'], name='montrek_exa_hub_id_6ac431_idx'),
        ),
        migrations.AddIndex(
            model_name='dhubvaluedate',
            index=models.Index(fields=['value_date_list'], name='montrek_exa_value_d_86fe6d_idx'),
        ),
        migrations.AddIndex(
            model_name='dhubvaluedate',
            index=models.Index(fields=['hub'], name='montrek_exa_hub_id_6f5972_idx'),
        ),
        migrations.AddIndex(
            model_name='ehubvaluedate',
            index=models.Index(fields=['value_date_list'], name='montrek_exa_value_d_ea477a_idx'),
        ),
        migrations.AddIndex(
            model_name='ehubvaluedate',
            index=models.Index(fields=['hub'], name='montrek_exa_hub_id_fc3ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_d71630_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_4e090f_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_38ec32_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1fieldmaphubvaluedate',
            index=models.Index(fields=['value_date_list'], name='montrek_exa_value_d_c6ffbd_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1fieldmaphubvaluedate',
            index=models.Index(fields=['hub'], name='montrek_exa_hub_id_ced8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='sata2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_c82720_idx'),
        ),
        migrations.AddIndex(
            model_name='sata2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_dcfb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='sata2',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_4cc1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='sata3',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_d6a93c_idx'),
        ),
        migrations.AddIndex(
            model_name='sata3',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_fe349b_idx'),
        ),
        migrations.AddIndex(
            model_name='sata3',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_54cd83_idx'),
        ),
        migrations.AddIndex(
            model_name='satb1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_fdc449_idx'),
        ),
        migrations.AddIndex(
            model_name='satb1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_25c411_idx'),
        ),
        migrations.AddIndex(
            model_name='satb1',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_bcb768_idx'),
        ),
        migrations.AddIndex(
            model_name='satb2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_e29177_idx'),
        ),
        migrations.AddIndex(
            model_name='satb2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_43a3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='satb2',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_22f632_idx'),
        ),
        migrations.AddIndex(
            model_name='satc1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_0d7135_idx'),
        ),
        migrations.AddIndex(
            model_name='satc1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_f9e9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='satc1',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_bb610e_idx'),
        ),
        migrations.AddIndex(
            model_name='satd1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_b64a93_idx'),
        ),
        migrations.AddIndex(
            model_name='satd1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_4311b6_idx'),
        ),
        migrations.AddIndex(
            model_name='satd1',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_90eafa_idx'),
        ),
        migrations.AddIndex(
            model_name='sate1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_ec934d_idx'),
        ),
        migrations.AddIndex(
            model_name='sate1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_1e47a2_idx'),
        ),
        migrations.AddIndex(
            model_name='sate1',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_2b88b8_idx'),
        ),
        migrations.AddIndex(
            model_name='sate2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_b40016_idx'),
        ),
        migrations.AddIndex(
            model_name='sate2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_94b3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='sate2',
            index=models.Index(fields=['hub_entity'], name='montrek_exa_hub_ent_49badb_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_883024_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_830258_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc2',
            index=models.Index(fields=['hub_value_date'], name='montrek_exa_hub_val_71f711_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc3',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_55d6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc3',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_205f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc3',
            index=models.Index(fields=['hub_value_date'], name='montrek_exa_hub_val_68a8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc4',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_e9ce9f_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc4',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_58ce25_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsc4',
            index=models.Index(fields=['hub_value_date'], name='montrek_exa_hub_val_90d541_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsd2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_89889b_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsd2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_32ee6d_idx'),
        ),
        migrations.AddIndex(
            model_name='sattsd2',
            index=models.Index(fields=['hub_value_date'], name='montrek_exa_hub_val_802351_idx'),
        ),
    ]
