# Generated by Django 4.2 on 2024-02-04 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HubA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HubB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HubC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatTSC2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("value_date", models.DateField()),
                ("field_tsc2_float", models.FloatField(default=0.0)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubc",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("field_c1_str", models.CharField(default="DEFAULT", max_length=50)),
                ("field_c1_bool", models.BooleanField(default=False)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubc",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatB2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("field_b2_str", models.CharField(default="DEFAULT", max_length=50)),
                (
                    "field_b2_choice",
                    models.CharField(
                        choices=[
                            ("CHOICE1", "Choice1"),
                            ("CHOICE2", "Choice2"),
                            ("CHOICE3", "Choice3"),
                        ],
                        default="CHOICE1",
                        max_length=10,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatB1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("field_b1_str", models.CharField(default="DEFAULT", max_length=50)),
                ("field_b1_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatA2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("field_a2_str", models.CharField(default="DEFAULT", max_length=50)),
                ("field_a2_float", models.FloatField(default=0.0)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.huba",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatA1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("field_a1_str", models.CharField(default="DEFAULT", max_length=50)),
                ("field_a1_int", models.IntegerField(default=0)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.huba",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkHubAHubC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.huba",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubc",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkHubAHubB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.huba",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="huba",
            name="link_hub_a_hub_b",
            field=models.ManyToManyField(
                related_name="link_hub_b_hub_a",
                through="montrek_example.LinkHubAHubB",
                to="montrek_example.hubb",
            ),
        ),
        migrations.AddField(
            model_name="huba",
            name="link_hub_a_hub_c",
            field=models.ManyToManyField(
                related_name="link_hub_c_hub_a",
                through="montrek_example.LinkHubAHubC",
                to="montrek_example.hubc",
            ),
        ),
        migrations.AddIndex(
            model_name="satc1",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_0d7135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satc1",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_f9e9d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satb2",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_e29177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satb2",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_43a3e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satb1",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_fdc449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satb1",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_25c411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata2",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_c82720_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata2",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_dcfb5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata1",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_d71630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata1",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_4e090f_idx"
            ),
        ),
    ]
