# Generated by Django 4.2 on 2024-03-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('montrek_example', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sattsc2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sattsc2',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc'),
        ),
        migrations.AddField(
            model_name='satd1',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satd1',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubd'),
        ),
        migrations.AddField(
            model_name='satc1',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satc1',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc'),
        ),
        migrations.AddField(
            model_name='satb2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satb2',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb'),
        ),
        migrations.AddField(
            model_name='satb1',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satb1',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb'),
        ),
        migrations.AddField(
            model_name='sata2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sata2',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba'),
        ),
        migrations.AddField(
            model_name='sata1',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sata1',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba'),
        ),
        migrations.AddField(
            model_name='linkhubbhubd',
            name='hub_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb'),
        ),
        migrations.AddField(
            model_name='linkhubbhubd',
            name='hub_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubd'),
        ),
        migrations.AddField(
            model_name='linkhubahubc',
            name='hub_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba'),
        ),
        migrations.AddField(
            model_name='linkhubahubc',
            name='hub_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc'),
        ),
        migrations.AddField(
            model_name='linkhubahubb',
            name='hub_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.huba'),
        ),
        migrations.AddField(
            model_name='linkhubahubb',
            name='hub_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb'),
        ),
        migrations.AddField(
            model_name='hubd',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hubc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hubb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hubb',
            name='link_hub_b_hub_d',
            field=models.ManyToManyField(related_name='link_hub_d_hub_b', through='montrek_example.LinkHubBHubD', to='montrek_example.hubd'),
        ),
        migrations.AddField(
            model_name='huba',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='huba',
            name='link_hub_a_hub_b',
            field=models.ManyToManyField(related_name='link_hub_b_hub_a', through='montrek_example.LinkHubAHubB', to='montrek_example.hubb'),
        ),
        migrations.AddField(
            model_name='huba',
            name='link_hub_a_hub_c',
            field=models.ManyToManyField(related_name='link_hub_c_hub_a', through='montrek_example.LinkHubAHubC', to='montrek_example.hubc'),
        ),
        migrations.AddIndex(
            model_name='satd1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_b64a93_idx'),
        ),
        migrations.AddIndex(
            model_name='satd1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_4311b6_idx'),
        ),
        migrations.AddIndex(
            model_name='satc1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_0d7135_idx'),
        ),
        migrations.AddIndex(
            model_name='satc1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_f9e9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='satb2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_e29177_idx'),
        ),
        migrations.AddIndex(
            model_name='satb2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_43a3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='satb1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_fdc449_idx'),
        ),
        migrations.AddIndex(
            model_name='satb1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_25c411_idx'),
        ),
        migrations.AddIndex(
            model_name='sata2',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_c82720_idx'),
        ),
        migrations.AddIndex(
            model_name='sata2',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_dcfb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1',
            index=models.Index(fields=['hash_identifier'], name='montrek_exa_hash_id_d71630_idx'),
        ),
        migrations.AddIndex(
            model_name='sata1',
            index=models.Index(fields=['hash_value'], name='montrek_exa_hash_va_4e090f_idx'),
        ),
    ]
