# Generated by Django 5.1.5 on 2025-05-17 17:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sata1",
            name="field_a1_int",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1000),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sata1",
            name="field_a1_str",
            field=models.CharField(
                blank=True, default="DEFAULT", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="field_b1_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="field_b1_str",
            field=models.CharField(
                blank=True, default="DEFAULT", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="HubARepositoryViewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_a1_str",
                    models.CharField(
                        blank=True, default="DEFAULT", max_length=50, null=True
                    ),
                ),
                (
                    "field_a1_int",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1000),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "field_a2_str",
                    models.CharField(
                        blank=True, default="DEFAULT", max_length=50, null=True
                    ),
                ),
                (
                    "field_a2_float",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "field_b1_str",
                    models.CharField(
                        blank=True, default="DEFAULT", max_length=50, null=True
                    ),
                ),
                (
                    "field_b1_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("value_date", models.DateTimeField(blank=True, null=True)),
                ("hub_entity_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("comment", models.CharField(blank=True, null=True)),
                ("value_date_list_id", models.IntegerField(blank=True, null=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.huba",
                    ),
                ),
            ],
            options={
                "db_table": "montrek_example_hubarepository_view_model",
                "managed": True,
            },
        ),
    ]
