# Generated by Django 4.2 on 2024-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0002_huba_created_by_hubb_created_by_hubc_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sata1",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sata2",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="satb1",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="satb2",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="satc1",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sattsc2",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
