# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0002_huba_state_date_end_huba_state_date_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huba',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='hubb',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='hubc',
            name='is_deleted',
        ),
    ]
