# Generated by Django 5.1.5 on 2025-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0002_hubarepositoryviewmodel_alter_sata1_field_a1_int_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hubarepositoryviewmodel",
            name="hub_entity_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
