# Generated by Django 4.2 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0003_sata1_comment_sata2_comment_satb1_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="huba",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="hubb",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="hubc",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="linkhubahubb",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="linkhubahubc",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sata1",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sata2",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="satb2",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="satc1",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sattsc2",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
