# Generated by Django 5.1.5 on 2025-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0003_hubarepositoryviewmodel_hub_entity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubarepositoryviewmodel",
            name="hub_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hubarepositoryviewmodel",
            name="value_date_list_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
