# Generated by Django 4.2 on 2024-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0003_linkhubafileuploadregistry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="satb1",
            name="data_quality_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="satb1",
            name="data_quality_status",
            field=models.CharField(
                choices=[("error", "Error"), ("warning", "Warning"), ("ok", "Ok")],
                default="ok",
                max_length=10,
            ),
        ),
    ]
