# Generated by Django 5.1.5 on 2025-05-18 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0003_alter_sata1_field_a1_int_alter_sata1_field_a1_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satb1',
            name='alert_level',
            field=models.CharField(blank=True, choices=[('error', 'error'), ('warning', 'warning'), ('ok', 'ok')], default='ok', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='satb2',
            name='field_b2_choice',
            field=models.CharField(blank=True, choices=[('CHOICE1', 'Choice1'), ('CHOICE2', 'Choice2'), ('CHOICE3', 'Choice3')], default='CHOICE1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='satb2',
            name='field_b2_str',
            field=models.CharField(blank=True, default='DEFAULT', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HubBRepositoryViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(blank=True, choices=[('error', 'error'), ('warning', 'warning'), ('ok', 'ok')], default='ok', max_length=10, null=True)),
                ('alert_message', models.CharField(blank=True, max_length=255, null=True)),
                ('field_b1_str', models.CharField(blank=True, default='DEFAULT', max_length=50, null=True)),
                ('field_b1_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('field_b2_str', models.CharField(blank=True, default='DEFAULT', max_length=50, null=True)),
                ('field_b2_choice', models.CharField(blank=True, choices=[('CHOICE1', 'Choice1'), ('CHOICE2', 'Choice2'), ('CHOICE3', 'Choice3')], default='CHOICE1', max_length=10, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('hub_entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.CharField(blank=True, null=True)),
                ('hub_d_id', models.CharField(blank=True, null=True)),
                ('field_d1_str', models.CharField(blank=True, null=True)),
                ('field_d1_int', models.CharField(blank=True, null=True)),
                ('value_date_list_id', models.IntegerField(blank=True, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb')),
            ],
            options={
                'db_table': 'montrek_example_hubbrepository_view_model',
                'managed': True,
            },
        ),
    ]
