# Generated by Django 5.1.5 on 2025-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0004_alter_satb1_alert_level_alter_satb2_field_b2_choice_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubarepositoryviewmodel",
            name="value_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hubbrepositoryviewmodel",
            name="value_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
