# Generated by Django 5.1.5 on 2025-05-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0004_hubarepositoryviewmodel_hub_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hubarepositoryviewmodel",
            name="hub_id",
        ),
        migrations.AddField(
            model_name="hubarepositoryviewmodel",
            name="hub",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.huba",
            ),
            preserve_default=False,
        ),
    ]
