# Generated by Django 4.2 on 2024-04-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0004_satb1_data_quality_message_satb1_data_quality_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="satb1",
            name="data_quality_status",
            field=models.CharField(
                choices=[("error", "error"), ("warning", "warning"), ("ok", "ok")],
                default="ok",
                max_length=10,
            ),
        ),
    ]
