# Generated by Django 4.2 on 2024-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0005_alter_satb1_data_quality_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualitySatB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_quality_status",
                    models.CharField(
                        choices=[
                            ("error", "error"),
                            ("warning", "warning"),
                            ("ok", "ok"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "data_quality_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="satb1",
            name="data_quality_message",
        ),
        migrations.RemoveField(
            model_name="satb1",
            name="data_quality_status",
        ),
    ]
