# Generated by Django 4.2 on 2024-04-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0005_alter_satb1_data_quality_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="satb1",
            old_name="data_quality_message",
            new_name="alert_message",
        ),
        migrations.RenameField(
            model_name="satb1",
            old_name="data_quality_status",
            new_name="alert_status",
        ),
    ]
