# Generated by Django 5.1.5 on 2025-05-22 19:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0005_alter_hubarepositoryviewmodel_value_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sata1",
            name="field_a1_int",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-1000),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sata1",
            name="field_a1_str",
            field=models.CharField(default="DEFAULT", max_length=50),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="alert_level",
            field=models.CharField(
                choices=[("error", "error"), ("warning", "warning"), ("ok", "ok")],
                default="ok",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="field_b1_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="field_b1_str",
            field=models.CharField(default="DEFAULT", max_length=50),
        ),
        migrations.AlterField(
            model_name="satb2",
            name="field_b2_choice",
            field=models.CharField(
                choices=[
                    ("CHOICE1", "Choice1"),
                    ("CHOICE2", "Choice2"),
                    ("CHOICE3", "Choice3"),
                ],
                default="CHOICE1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="satb2",
            name="field_b2_str",
            field=models.CharField(default="DEFAULT", max_length=50),
        ),
    ]
