# Generated by Django 4.2 on 2024-04-13 21:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "montrek_example",
            "0006_dataqualitysatb_remove_satb1_data_quality_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dataqualitysatb",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="hash_identifier",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="hash_value",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="hub_entity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.hubb",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="state_date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="state_date_start",
            field=models.DateTimeField(
                default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AddField(
            model_name="dataqualitysatb",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
