# Generated by Django 4.2 on 2024-03-25 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0006_hubd_satd1_satd1_montrek_exa_hash_id_b64a93_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHubBHubD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubb')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubd')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
