# Generated by Django 4.2 on 2024-04-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0006_rename_data_quality_message_satb1_alert_message_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="satb1",
            old_name="alert_status",
            new_name="alert_level",
        ),
    ]
