# Generated by Django 4.2 on 2024-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0007_linkhubbhubd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubb',
            name='link_hub_b_hub_d',
            field=models.ManyToManyField(related_name='link_hub_d_hub_b', through='montrek_example.LinkHubBHubD', to='montrek_example.hubd'),
        ),
    ]
