# Generated by Django 5.0.4 on 2024-04-26 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_upload", "0002_rename_endpoint_apiuploadregistrystaticsatellite_url"),
        ("montrek_example", "0007_rename_alert_status_satb1_alert_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkHubAApiUploadRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.huba",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_upload.apiuploadregistryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="huba",
            name="link_hub_a_api_upload_registry",
            field=models.ManyToManyField(
                related_name="link_api_upload_registry_hub_a",
                through="montrek_example.LinkHubAApiUploadRegistry",
                to="api_upload.apiuploadregistryhub",
            ),
        ),
    ]
