# Generated by Django 5.1.5 on 2025-08-22 08:56

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0008_sata5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sata5",
            name="secret_field",
            field=encrypted_fields.fields.EncryptedCharField(
                default="SECRET", max_length=24, null=True
            ),
        ),
    ]
