# Generated by Django 5.1.5 on 2025-10-03 08:56

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0009_alter_sata5_secret_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkHubDHubE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubd",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hube",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="hubd",
            name="link_hub_d_hub_e",
            field=models.ManyToManyField(
                related_name="link_hub_e_hub_d",
                through="montrek_example.LinkHubDHubE",
                to="montrek_example.hube",
            ),
        ),
    ]
