# Generated by Django 5.0.4 on 2024-05-25 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_fileuploadregistryhub_and_more'),
        ('montrek_example', '0009_fileuploadregistryhub_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadregistryhub',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fileuploadregistryhub',
            name='link_file_upload_registry_file_upload_file',
        ),
        migrations.RenameModel(
            old_name='LinkFileUploadRegistryFileUploadFile',
            new_name='LinkHubAFileUploadRegistryFileUploadFile',
        ),
        migrations.CreateModel(
            name='HubAFileUploadRegistryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('link_file_upload_registry_file_upload_file', models.ManyToManyField(related_name='link_file_upload_file_hub_a_file_upload_registry', through='montrek_example.LinkHubAFileUploadRegistryFileUploadFile', to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='huba',
            name='link_hub_a_file_upload_registry',
            field=models.ManyToManyField(related_name='link_file_upload_registry_hub_a', through='montrek_example.LinkHubAFileUploadRegistry', to='montrek_example.hubafileuploadregistryhub'),
        ),
        migrations.AlterField(
            model_name='linkhubafileuploadregistry',
            name='hub_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub'),
        ),
        migrations.AlterField(
            model_name='linkhubafileuploadregistryfileuploadfile',
            name='hub_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub'),
        ),
        migrations.DeleteModel(
            name='FileUploadRegistryStaticSatellite',
        ),
        migrations.DeleteModel(
            name='FileUploadRegistryHub',
        ),
    ]
