# Generated by Django 5.0.4 on 2024-05-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0010_hubaapiuploadregistryhub_and_more'),
        ('montrek_example', '0010_sata1fieldmaphub_sata1fieldmapstaticsatellite'),
    ]

    operations = [
    ]
