# Generated by Django 5.1.5 on 2025-10-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0010_linkhubdhube_hubd_link_hub_d_hub_e"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubCRepositoryViewModelViewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_tsc2_float",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("hub_entity_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("comment", models.CharField(blank=True, null=True)),
                ("value_date_list_id", models.IntegerField(blank=True, null=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubc",
                    ),
                ),
            ],
            options={
                "db_table": "montrek_example_hubcrepositoryviewmodel_view_model",
                "managed": True,
            },
        ),
    ]
