# Generated by Django 5.0.4 on 2024-06-21 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0011_rename_linkfileuploadregistrylogexcelfile_linkfileuploadregistrylogfile_and_more'),
        ('montrek_example', '0011_merge_20240527_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHubAFileUploadRegistryFileLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubafileuploadregistryhub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubafileuploadregistryhub',
            name='link_file_upload_registry_file_log_file',
            field=models.ManyToManyField(related_name='link_file_log_file_hub_a_file_upload_registry', through='montrek_example.LinkHubAFileUploadRegistryFileLogFile', to='file_upload.fileuploadfilehub'),
        ),
    ]
