# Generated by Django 5.2.9 on 2025-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0012_satcboolean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubbrepositoryviewmodel",
            name="alert_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("error", "error"),
                    ("warning", "warning"),
                    ("ok", "ok"),
                    ("unknown", "unknown"),
                ],
                default="ok",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="satb1",
            name="alert_level",
            field=models.CharField(
                choices=[
                    ("error", "error"),
                    ("warning", "warning"),
                    ("ok", "ok"),
                    ("unknown", "unknown"),
                ],
                default="ok",
                max_length=10,
            ),
        ),
    ]
