# Generated by Django 5.0.4 on 2024-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0012_linkhubafileuploadregistryfilelogfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sata2',
            name='field_a2_str',
            field=models.CharField(blank=True, default='DEFAULT', max_length=50, null=True),
        ),
    ]
