# Generated by Django 5.0.4 on 2024-07-27 06:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0013_alter_sata2_field_a2_str'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatTSC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('field_tsc3_int', models.IntegerField(default=0)),
                ('field_tsc3_str', models.CharField(default='DEFAULT', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrek_example.hubc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
