# Generated by Django 5.2.9 on 2026-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0013_alter_hubbrepositoryviewmodel_alert_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hubbrepositoryviewmodel",
            name="hub_d_id",
        ),
        migrations.AlterField(
            model_name="hubarepositoryviewmodel",
            name="created_by",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hubbrepositoryviewmodel",
            name="created_by",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hubbrepositoryviewmodel",
            name="field_d1_int",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="hubbrepositoryviewmodel",
            name="field_d1_str",
            field=models.CharField(
                blank=True, default="DEFAULT", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hubcrepositoryviewmodelviewmodel",
            name="created_by",
            field=models.CharField(blank=True, null=True),
        ),
    ]
