# Generated by Django 5.2.9 on 2026-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0014_alter_hubafileuploadregistrystaticsatellite_file_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hubaapiuploadregistrystaticsatellite",
            name="celery_task_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
