# Generated by Django 5.0.4 on 2024-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0014_sattsc3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sattsc3',
            name='field_tsc3_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sattsc3',
            name='field_tsc3_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
