# Generated by Django 5.0.4 on 2024-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0016_sattsc4"),
    ]

    operations = [
        migrations.AddField(
            model_name="sata1fieldmapstaticsatellite",
            name="step",
            field=models.IntegerField(default=1),
        ),
    ]
