# Generated by Django 5.0.4 on 2024-09-19 15:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0017_sata1fieldmapstaticsatellite_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='sattsc3',
            name='field_tsc3_int_times_two',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('field_tsc3_int'), '*', models.Value(2)), output_field=models.IntegerField()),
        ),
    ]
