# Generated by Django 5.0.4 on 2024-11-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0020_sata3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sattsc2",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="hash_identifier",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="hash_value",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="hub_entity",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="state_date_end",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="state_date_start",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="value_date",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="hash_identifier",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="hash_value",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="hub_entity",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="state_date_end",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="state_date_start",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="value_date",
        ),
        migrations.CreateModel(
            name="CHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_date", models.DateField()),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="montrek_example.hubc",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sattsc2",
            name="hub_value_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.chubvaluedate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sattsc3",
            name="hub_value_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.chubvaluedate",
            ),
            preserve_default=False,
        ),
    ]
