# Generated by Django 5.0.4 on 2024-11-10 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0003_valuedatelist"),
        ("montrek_example", "0020_sata3"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="hub_entity",
        ),
        migrations.RemoveField(
            model_name="sattsc2",
            name="value_date",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="hub_entity",
        ),
        migrations.RemoveField(
            model_name="sattsc3",
            name="value_date",
        ),
        migrations.RemoveField(
            model_name="sattsc4",
            name="hub_entity",
        ),
        migrations.RemoveField(
            model_name="sattsc4",
            name="value_date",
        ),
        migrations.RemoveField(
            model_name="sattsd2",
            name="hub_entity",
        ),
        migrations.RemoveField(
            model_name="sattsd2",
            name="value_date",
        ),
        migrations.CreateModel(
            name="CHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="montrek_example.hubc",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sattsc2",
            name="hub_value_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.chubvaluedate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sattsc3",
            name="hub_value_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.chubvaluedate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sattsc4",
            name="hub_value_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.chubvaluedate",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="sattsc2",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_883024_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc2",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_830258_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc3",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_55d6e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc3",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_205f9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc4",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_e9ce9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc4",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_58ce25_idx"
            ),
        ),
        migrations.AddField(
            model_name="dhubvaluedate",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="montrek_example.hubd",
            ),
        ),
        migrations.AddField(
            model_name="dhubvaluedate",
            name="value_date_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="baseclasses.valuedatelist",
            ),
        ),
        migrations.AddField(
            model_name="sattsd2",
            name="hub_value_date",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="montrek_example.dhubvaluedate",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="sattsd2",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_89889b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsd2",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_32ee6d_idx"
            ),
        ),
    ]
