# Generated by Django 5.0.4 on 2024-11-14 12:49

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0005_alter_testhubvaluedate_hub"),
        ("montrek_example", "0021_dhubvaluedate_remove_sattsc2_hub_entity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ahubvaluedate",
            name="hub",
            field=baseclasses.fields.HubForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="montrek_example.huba",
            ),
        ),
        migrations.AlterField(
            model_name="bhubvaluedate",
            name="hub",
            field=baseclasses.fields.HubForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="montrek_example.hubb",
            ),
        ),
        migrations.AlterField(
            model_name="chubvaluedate",
            name="hub",
            field=baseclasses.fields.HubForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="montrek_example.hubc",
            ),
        ),
        migrations.AlterField(
            model_name="dhubvaluedate",
            name="hub",
            field=baseclasses.fields.HubForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="montrek_example.hubd",
            ),
        ),
        migrations.CreateModel(
            name="HubAApiUploadRegistryHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="montrek_example.hubaapiuploadregistryhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatA1FieldMapHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="montrek_example.sata1fieldmaphub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
