# Generated by Django 5.0.4 on 2024-11-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0021_dhubvaluedate_hubaapiuploadregistryhubvaluedate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sata2",
            name="field_a2_float",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
