# Generated by Django 5.0.4 on 2024-11-09 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0021_valuedatelist_remove_sattsc2_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sattsc4",
            index=models.Index(
                fields=["hash_identifier"], name="montrek_exa_hash_id_e9ce9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc4",
            index=models.Index(
                fields=["hash_value"], name="montrek_exa_hash_va_58ce25_idx"
            ),
        ),
    ]
