# Generated by Django 5.0.4 on 2024-11-10 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0004_testhubvaluedate"),
        ("montrek_example", "0021_dhubvaluedate_remove_sattsc2_hub_entity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="montrek_example.huba",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="montrek_example.hubb",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
