# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more",
        ),
        ("montrek_example", "0022_alter_sata2_field_a2_float"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ahubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_7d85d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ahubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_928aa0_idx"),
        ),
        migrations.AddIndex(
            model_name="bhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_23ba80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bhubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_c4e75c_idx"),
        ),
        migrations.AddIndex(
            model_name="chubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_383509_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_6ac431_idx"),
        ),
        migrations.AddIndex(
            model_name="dhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_86fe6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dhubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_6f5972_idx"),
        ),
        migrations.AddIndex(
            model_name="hubaapiuploadregistryhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_d07c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hubaapiuploadregistryhubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_d40b2a_idx"),
        ),
        migrations.AddIndex(
            model_name="hubafileuploadregistryhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_23fc7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hubafileuploadregistryhubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_35bb87_idx"),
        ),
        migrations.AddIndex(
            model_name="sata1",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_38ec32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata1fieldmaphubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="montrek_exa_value_d_c6ffbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata1fieldmaphubvaluedate",
            index=models.Index(fields=["hub"], name="montrek_exa_hub_id_ced8d3_idx"),
        ),
        migrations.AddIndex(
            model_name="sata2",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_4cc1c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sata3",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_54cd83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satb1",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_bcb768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satb2",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_22f632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satc1",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_bb610e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="satd1",
            index=models.Index(
                fields=["hub_entity"], name="montrek_exa_hub_ent_90eafa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc2",
            index=models.Index(
                fields=["hub_value_date"], name="montrek_exa_hub_val_71f711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc3",
            index=models.Index(
                fields=["hub_value_date"], name="montrek_exa_hub_val_68a8d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsc4",
            index=models.Index(
                fields=["hub_value_date"], name="montrek_exa_hub_val_90d541_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sattsd2",
            index=models.Index(
                fields=["hub_value_date"], name="montrek_exa_hub_val_802351_idx"
            ),
        ),
    ]
