# Generated by Django 5.0.4 on 2024-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "montrek_example",
            "0024_alter_sata2_field_a2_float_hube_ehubvaluedate_sate1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sata2",
            name="field_a2_float",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
