# Generated by Django 5.1.5 on 2025-02-21 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("montrek_example", "0025_alter_sata2_field_a2_float"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sata1",
            name="field_a1_int",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-1000),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
