# Generated by Django 5.1.5 on 2025-03-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrek_example', '0026_alter_sata1_field_a1_int'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubaapiuploadregistrystaticsatellite',
            old_name='upload_message',
            new_name='import_message',
        ),
        migrations.RenameField(
            model_name='hubaapiuploadregistrystaticsatellite',
            old_name='upload_status',
            new_name='import_status',
        ),
        migrations.RemoveField(
            model_name='hubaapiuploadregistrystaticsatellite',
            name='url',
        ),
        migrations.AddField(
            model_name='hubaapiuploadregistrystaticsatellite',
            name='import_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
