# Generated by Django 4.2 on 2023-06-22 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("transaction_date", models.DateTimeField()),
                ("transaction_amount", models.IntegerField()),
                (
                    "transaction_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transaction_type", models.CharField(max_length=50)),
                ("transaction_description", models.CharField(max_length=50)),
                ("transaction_category", models.CharField(max_length=50)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
