# Generated by Django 4.2 on 2023-07-19 10:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                (
                    "state_date_start",
                    models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
                    ),
                ),
                ("transaction_date", models.DateTimeField()),
                ("transaction_amount", models.IntegerField()),
                (
                    "transaction_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transaction_type", models.CharField(max_length=50)),
                ("transaction_description", models.TextField()),
                ("transaction_category", models.CharField(max_length=50)),
                ("transaction_party", models.CharField(default="NONE", max_length=250)),
                (
                    "transaction_party_iban",
                    models.CharField(
                        default="XX00000000000000000000",
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid IBAN format.",
                                regex="^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$",
                            )
                        ],
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="transactionsatellite",
            index=models.Index(
                fields=["hash_identifier"], name="transaction_hash_id_a62048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionsatellite",
            index=models.Index(
                fields=["hash_value"], name="transaction_hash_va_77625a_idx"
            ),
        ),
    ]
