# Generated by Django 4.2 on 2023-05-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsatellite',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionsatellite',
            name='transaction_amount',
            field=models.IntegerField(),
        ),
    ]
