# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategoryhub',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='transactioncategorymaphub',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='transactionhub',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='transactiontypehub',
            name='is_deleted',
        ),
    ]
