# Generated by Django 4.2 on 2023-07-21 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTypeHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionTypeSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("typename", models.CharField(default="NONE", max_length=50)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                (
                    "state_date_start",
                    models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactiontypehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionTransactionTypeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactionhub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactiontypehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="transactiontypesatellite",
            index=models.Index(
                fields=["hash_identifier"], name="transaction_hash_id_eb8739_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontypesatellite",
            index=models.Index(
                fields=["hash_value"], name="transaction_hash_va_b5c18a_idx"
            ),
        ),
    ]
