# Generated by Django 4.2 on 2023-05-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactionsatellite_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionhub'),
        ),
    ]
