# Generated by Django 4.2 on 2023-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_linktransactionasset_state_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linktransactionasset',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linktransactionasset',
            old_name='out_hub',
            new_name='hub_out',
        ),
        migrations.RenameField(
            model_name='linktransactiontransactioncategory',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linktransactiontransactioncategory',
            old_name='out_hub',
            new_name='hub_out',
        ),
        migrations.RenameField(
            model_name='linktransactiontransactiontype',
            old_name='in_hub',
            new_name='hub_in',
        ),
        migrations.RenameField(
            model_name='linktransactiontransactiontype',
            old_name='out_hub',
            new_name='hub_out',
        ),
    ]
