# Generated by Django 4.2 on 2023-07-21 04:47

from django.db import migrations

def get_hashes(apps, schema_editor):
    TransactionTypeSatellite = apps.get_model('transaction', 'TransactionTypeSatellite')
    for transaction_type in TransactionTypeSatellite.objects.all():
        transaction_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_auto_20230721_0429"),
    ]

    operations = [
        migrations.RunPython(get_hashes),
    ]
