# Generated by Django 4.2 on 2023-12-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactioncategoryhub_state_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategorymapsatellite',
            name='hash_searchfield',
        ),
    ]
