# Generated by Django 4.2 on 2023-07-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_auto_20230721_0447"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionsatellite",
            name="transaction_type",
        ),
    ]
