# Generated by Django 4.2 on 2023-07-23 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0005_remove_transactionsatellite_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategoryHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="transactionsatellite",
            name="transaction_category",
        ),
        migrations.CreateModel(
            name="TransactionTransactionCategoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactionhub",
                    ),
                ),
                (
                    "to_hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactioncategoryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionCategorySatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("typename", models.CharField(default="NONE", max_length=50)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                (
                    "state_date_start",
                    models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactioncategoryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="transactioncategorysatellite",
            index=models.Index(
                fields=["hash_identifier"], name="transaction_hash_id_fad1a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactioncategorysatellite",
            index=models.Index(
                fields=["hash_value"], name="transaction_hash_va_693983_idx"
            ),
        ),
    ]
