# Generated by Django 4.2 on 2024-01-03 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accounthub_state_date_end_and_more'),
        ('transaction', '0005_remove_transactioncategorymapsatellite_hash_searchfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTransactionCategoryMapCounterTransactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactioncategorymaphub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounthub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactioncategorymaphub',
            name='link_transaction_category_map_counter_transaction_account',
            field=models.ManyToManyField(related_name='link_counter_transaction_account_transaction_category_map', through='transaction.LinkTransactionCategoryMapCounterTransactionAccount', to='account.accounthub'),
        ),
    ]
