# Generated by Django 4.2 on 2023-07-24 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0006_transactioncategoryhub_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategoryMapHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionCategoryMapSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                (
                    "state_date_start",
                    models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
                    ),
                ),
                ("field", models.CharField(default="NONE", max_length=250)),
                ("value", models.CharField(default="NONE", max_length=250)),
                ("category", models.CharField(default="NONE", max_length=250)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transactioncategoryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="transactioncategorymapsatellite",
            index=models.Index(
                fields=["hash_identifier"], name="transaction_hash_id_109230_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactioncategorymapsatellite",
            index=models.Index(
                fields=["hash_value"], name="transaction_hash_va_484a71_idx"
            ),
        ),
    ]
