# Generated by Django 4.2 on 2023-07-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0007_transactioncategorymaphub_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategorymapsatellite",
            name="hub_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transactioncategorymaphub",
            ),
        ),
    ]
