# Generated by Django 4.2 on 2023-07-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0008_alter_transactioncategorymapsatellite_hub_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactioncategorymapsatellite",
            name="hash_searchfield",
            field=models.CharField(default="", max_length=64),
        ),
    ]
