# Generated by Django 4.2 on 2023-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0009_transactioncategorymapsatellite_hash_searchfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhub",
            name="link_transaction_transaction_category",
            field=models.ManyToManyField(
                related_name="link_transaction_category_transaction",
                to="transaction.transactioncategoryhub",
            ),
        ),
        migrations.AddField(
            model_name="transactionhub",
            name="link_transaction_transaction_type",
            field=models.ManyToManyField(
                related_name="link_transaction_type_transaction",
                to="transaction.transactiontypehub",
            ),
        ),
    ]
