# Generated by Django 4.2 on 2023-08-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction",
            "0010_transactionhub_link_transaction_transaction_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiontransactiontypelink",
            name="from_hub",
        ),
        migrations.RemoveField(
            model_name="transactiontransactiontypelink",
            name="to_hub",
        ),
        migrations.DeleteModel(
            name="TransactionTransactionCategoryLink",
        ),
        migrations.DeleteModel(
            name="TransactionTransactionTypeLink",
        ),
    ]
