# Generated by Django 4.2 on 2023-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_remove_transactiontransactiontypelink_from_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategorymapsatellite',
            name='field',
            field=models.CharField(choices=[('transaction_party', 'Transaction Party'), ('transaction_party_iban', 'Transaction Party IBAN')], default='transaction_party', max_length=25),
        ),
        migrations.AlterField(
            model_name='transactionhub',
            name='link_transaction_transaction_type',
            field=models.ManyToManyField(related_name='link_transaction_transaction_type', to='transaction.transactiontypehub'),
        ),
    ]
