# Generated by Django 4.2 on 2023-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_transactioncategorymapsatellite_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategoryhub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactioncategorymaphub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionhub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontypehub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactioncategorymapsatellite',
            name='category',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='transactioncategorymapsatellite',
            name='value',
            field=models.CharField(default='', max_length=250),
        ),
    ]
