# Generated by Django 4.2 on 2023-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_transactioncategoryhub_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategorysatellite',
            name='is_regex',
            field=models.BooleanField(default=False),
        ),
    ]
