# Generated by Django 4.2 on 2023-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_transactioncategorysatellite_is_regex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategorysatellite',
            name='is_regex',
        ),
        migrations.AddField(
            model_name='transactioncategorymapsatellite',
            name='is_regex',
            field=models.BooleanField(default=False),
        ),
    ]
