# Generated by Django 4.2 on 2023-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('transaction', '0015_remove_transactioncategorysatellite_is_regex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhub',
            name='link_transaction_asset',
            field=models.ManyToManyField(related_name='link_asset_transaction', to='asset.assethub'),
        ),
    ]
