# Generated by Django 4.2 on 2023-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_transactionhub_link_transaction_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsatellite',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
