# Generated by Django 4.2 on 2023-10-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_alter_transactionsatellite_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_satellite', to='transaction.transactionhub'),
        ),
    ]
