# Generated by Django 4.2 on 2024-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaticsatellite',
            name='share_class_figi',
            field=models.CharField(default='', max_length=255),
        ),
    ]
