# Generated by Django 4.2 on 2024-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companystaticsatellite_share_class_figi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaticsatellite',
            name='share_class_figi',
            field=models.CharField(max_length=255),
        ),
    ]
