# Generated by Django 4.2 on 2024-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_linkcompanyfileuploadregistry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companytimeseriessatellite",
            name="total_revenue",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
