# Generated by Django 5.2.9 on 2026-02-03 08:55

import baseclasses.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseclasses", "0026_delete_mockmodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadRegistryHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("identifier", models.CharField(default="", max_length=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadRegistryHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="download_registry.downloadregistryhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["value_date_list"],
                        name="download_re_value_d_46c05c_idx",
                    ),
                    models.Index(fields=["hub"], name="download_re_hub_id_533d22_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DownloadRegistrySatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("download_name", models.CharField()),
                (
                    "dowload_type",
                    models.CharField(
                        choices=[
                            ("xlsx", "xlsx"),
                            ("csv", "csv"),
                            ("api", "api"),
                            ("pdf", "pdf"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="download_registry.downloadregistryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["hash_identifier"],
                        name="download_re_hash_id_48387c_idx",
                    ),
                    models.Index(
                        fields=["hash_value"], name="download_re_hash_va_8c2a14_idx"
                    ),
                    models.Index(
                        fields=["hub_entity"], name="download_re_hub_ent_ba558f_idx"
                    ),
                ],
            },
        ),
    ]
