# Generated by Django 4.2 on 2024-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="montrekuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="montrekuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="montrekuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
