# Generated by Django 4.2 on 2024-02-04 09:51

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='montrekuser',
            managers=[
                ('objects', user.models.MontrekUserManager()),
            ],
        ),
    ]
