# Generated by Django 4.2 on 2024-02-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_montrekuser_managers'),
        ('user', '0002_alter_montrekuser_managers_and_more'),
    ]

    operations = [
    ]
