# Generated by Django 5.1.5 on 2025-02-05 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_montrekuserhub_montrekuserhubvaluedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="montrekusersatellite",
            name="montrek_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="montrek_user_satellites",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
