# Generated by Django 5.2.9 on 2026-07-01 09:46

from django.db import migrations


def backfill_user_assignments(apps, schema_editor):
    User = apps.get_model("user", "MontrekUser")
    UserAssignmentHub = apps.get_model("user", "UserAssignmentHub")
    UserAssignmentHubValueDate = apps.get_model("user", "UserAssignmentHubValueDate")
    UserAssignmentSatellite = apps.get_model("user", "UserAssignmentSatellite")
    ValueDateList = apps.get_model("baseclasses", "ValueDateList")

    value_date_list, _ = ValueDateList.objects.get_or_create(value_date=None)

    already_registered = set(
        UserAssignmentSatellite.objects.values_list("user_id", flat=True)
    )

    for user in User.objects.exclude(pk__in=already_registered):
        hub = UserAssignmentHub.objects.create()
        UserAssignmentHubValueDate.objects.create(
            hub=hub, value_date_list=value_date_list
        )
        UserAssignmentSatellite.objects.create(hub_entity=hub, user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userassignmenthub_userassignmenthubvaluedate_and_more"),
        ("baseclasses", "__first__"),
    ]

    operations = [
        migrations.RunPython(
            backfill_user_assignments,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
