# Generated by Django 4.2 on 2024-02-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20240207_1953'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='montrekuser',
            managers=[
            ],
        ),
    ]
