# Generated by Django 5.1.5 on 2025-02-05 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_montrekusersatellite_montrek_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="montrekusersatellite",
            name="montrek_user",
        ),
        migrations.AddField(
            model_name="montrekusersatellite",
            name="montrek_user_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="montrekusersatellite",
            name="related_montrek_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="related_montrek_user_satellites",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
