# Generated by Django 5.2.9 on 2026-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_backfill_user_assignment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userassignmentsatellite",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_assignment_satellite_per_user"
            ),
        ),
    ]
