# Generated by Django 5.1.5 on 2025-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_montrekusersatellite_montrek_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="montrekusersatellite",
            name="related_montrek_user",
        ),
    ]
