# Generated by Django 5.1.5 on 2025-03-23 12:48

import baseclasses.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseclasses', '0008_testmontrektimeseriessatellite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRegistryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRegistrySatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('import_message', models.TextField(default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_import.apiregistryhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRegistryHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='api_import.apiregistryhub')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['value_date_list'], name='api_import__value_d_1cf4f2_idx'), models.Index(fields=['hub'], name='api_import__hub_id_72179d_idx')],
            },
        ),
    ]
