# Generated by Django 5.1.5 on 2025-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiregistrysatellite',
            name='import_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
