# Generated by Django 5.1.5 on 2025-03-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_import', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockapiregistryhubvaluedate',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='mockapiregistrysatellite',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='mockapiregistryhubvaluedate',
            name='value_date_list',
        ),
        migrations.RemoveField(
            model_name='mockapiregistrysatellite',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MockApiRegistryHub',
        ),
        migrations.DeleteModel(
            name='MockApiRegistryHubValueDate',
        ),
        migrations.DeleteModel(
            name='MockApiRegistrySatellite',
        ),
    ]
