# Generated by Django 5.2.9 on 2026-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_import", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockapiregistrysatellite",
            name="celery_task_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
