# Generated by Django 5.1.5 on 2025-03-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_import', '0002_apiregistrysatellite_import_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiregistrysatellite',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='apiregistryhubvaluedate',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='apiregistryhubvaluedate',
            name='value_date_list',
        ),
        migrations.RemoveField(
            model_name='apiregistrysatellite',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ApiRegistryHub',
        ),
        migrations.DeleteModel(
            name='ApiRegistryHubValueDate',
        ),
        migrations.DeleteModel(
            name='ApiRegistrySatellite',
        ),
    ]
