# Generated by Django 5.0.4 on 2024-12-09 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stransactionhub",
            name="link_stransaction_sproduct",
            field=models.ManyToManyField(
                related_name="link_sproduct_stransaction",
                through="showcase.LinkSTransactionSProduct",
                to="showcase.sproducthub",
            ),
        ),
        migrations.CreateModel(
            name="LinkSTransactionSAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.stransactionhub",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.sassethub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="stransactionhub",
            name="link_stransaction_sasset",
            field=models.ManyToManyField(
                related_name="link_sasset_stransaction",
                through="showcase.LinkSTransactionSAsset",
                to="showcase.sassethub",
            ),
        ),
    ]
