# Generated by Django 5.0.4 on 2024-12-07 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more",
        ),
        ("showcase", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PositionHub",
            new_name="SPositionHub",
        ),
        migrations.RenameModel(
            old_name="PositionHubValueDate",
            new_name="SPositionHubValueDate",
        ),
        migrations.RenameField(
            model_name="sassetstaticsatellite",
            old_name="asset_name",
            new_name="sasset_name",
        ),
        migrations.RenameField(
            model_name="sassettypesatellite",
            old_name="asset_type",
            new_name="sasset_type",
        ),
        migrations.RenameField(
            model_name="sproductsatellite",
            old_name="product_name",
            new_name="sproduct_name",
        ),
        migrations.RenameField(
            model_name="stransactionsatellite",
            old_name="transaction_description",
            new_name="stransaction_description",
        ),
        migrations.RenameField(
            model_name="stransactionsatellite",
            old_name="transaction_external_identifier",
            new_name="stransaction_external_identifier",
        ),
        migrations.RenameField(
            model_name="stransactionsatellite",
            old_name="transaction_price",
            new_name="stransaction_price",
        ),
        migrations.RenameField(
            model_name="stransactionsatellite",
            old_name="transaction_quantity",
            new_name="stransaction_quantity",
        ),
        migrations.RenameIndex(
            model_name="spositionhubvaluedate",
            new_name="showcase_sp_value_d_b073c7_idx",
            old_name="showcase_po_value_d_15beba_idx",
        ),
        migrations.RenameIndex(
            model_name="spositionhubvaluedate",
            new_name="showcase_sp_hub_id_648c6e_idx",
            old_name="showcase_po_hub_id_86b5a9_idx",
        ),
    ]
