# Generated by Django 5.0.4 on 2024-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0002_stransactionhub_link_stransaction_sproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sassetstaticsatellite",
            name="asset_isin",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
