# Generated by Django 5.0.4 on 2024-12-10 10:22

import baseclasses.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more",
        ),
        ("showcase", "0003_sassetstaticsatellite_asset_isin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SCompanyHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("identifier", models.CharField(default="", max_length=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkSAssetSCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.sassethub",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.scompanyhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sassethub",
            name="link_sasset_scompany",
            field=models.ManyToManyField(
                related_name="link_scompany_sasset",
                through="showcase.LinkSAssetSCompany",
                to="showcase.scompanyhub",
            ),
        ),
        migrations.CreateModel(
            name="SCompanyHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="showcase.scompanyhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["value_date_list"],
                        name="showcase_sc_value_d_f9bc97_idx",
                    ),
                    models.Index(fields=["hub"], name="showcase_sc_hub_id_6abc45_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SCompanyStaticSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.scompanyhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["hash_identifier"],
                        name="showcase_sc_hash_id_923bb8_idx",
                    ),
                    models.Index(
                        fields=["hash_value"], name="showcase_sc_hash_va_e78e35_idx"
                    ),
                    models.Index(
                        fields=["hub_entity"], name="showcase_sc_hub_ent_8de9b2_idx"
                    ),
                ],
            },
        ),
    ]
