# Generated by Django 5.0.4 on 2024-12-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0004_scompanyhub_linksassetscompany_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spositionhubvaluedate",
            name="hub",
        ),
        migrations.RemoveField(
            model_name="spositionhubvaluedate",
            name="value_date_list",
        ),
        migrations.DeleteModel(
            name="SPositionHub",
        ),
        migrations.DeleteModel(
            name="SPositionHubValueDate",
        ),
    ]
