# Generated by Django 5.0.4 on 2024-12-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase", "0005_remove_spositionhubvaluedate_hub_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stransactionsatellite",
            name="showcase_st_hub_val_0ce75b_idx",
        ),
        migrations.RenameField(
            model_name="stransactionsatellite",
            old_name="value_date",
            new_name="transaction_date",
        ),
        migrations.RemoveField(
            model_name="stransactionsatellite",
            name="hub_value_date",
        ),
        migrations.AddField(
            model_name="stransactionsatellite",
            name="hub_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="showcase.stransactionhub",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="stransactionsatellite",
            index=models.Index(
                fields=["hub_entity"], name="showcase_st_hub_ent_4bcc6a_idx"
            ),
        ),
    ]
