# Generated by Django 5.0.4 on 2024-12-06 14:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "showcase",
            "0005_positionhub_positionhubvaluedate_positionsatellite_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.transactionhub",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.producthub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
