# Generated by Django 5.0.4 on 2024-12-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0006_linkproducttransaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LinkProductTransaction",
            new_name="LinkTransactionProduct",
        ),
    ]
