# Generated by Django 5.0.4 on 2024-12-13 18:14

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0007_linkstransactionfuregistryfufile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stransactionfuregistryhubvaluedate",
            name="hub",
            field=baseclasses.fields.HubForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="showcase.stransactionfuregistryhub",
            ),
        ),
    ]
