# Generated by Django 5.0.4 on 2025-01-07 11:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "country",
            "0011_countryapiuploadregistryhubvaluedate_country_cou_value_d_828faa_idx_and_more",
        ),
        (
            "file_upload",
            "0016_fieldmaphubvaluedate_file_upload_value_d_063842_idx_and_more",
        ),
        ("showcase", "0008_alter_stransactionfuregistryhubvaluedate_hub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stransactionfuregistryhub",
            name="link_file_upload_registry_file_upload_file",
            field=models.ManyToManyField(
                related_name="link_stransaction_file_upload_file_file_upload_registry",
                through="showcase.LinkSTransactionFURegistryFUFile",
                to="file_upload.fileuploadfilehub",
            ),
        ),
        migrations.CreateModel(
            name="LinkSCompanyCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showcase.scompanyhub",
                    ),
                ),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.countryhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="scompanyhub",
            name="link_scompany_country",
            field=models.ManyToManyField(
                related_name="link_country_scompany",
                through="showcase.LinkSCompanyCountry",
                to="country.countryhub",
            ),
        ),
    ]
