# Generated by Django 5.0.4 on 2025-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "showcase",
            "0009_alter_stransactionfuregistryhub_link_file_upload_registry_file_upload_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scompanystaticsatellite",
            name="company_sector",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
