# Generated by Django 5.2.9 on 2026-05-06 19:22

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0028_delete_mockmodel"),
        ("file_export", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestFileExportRegistryHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="file_export.testfileexportregistryhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["value_date_list"],
                        name="file_export_value_d_2c1d4b_idx",
                    ),
                    models.Index(fields=["hub"], name="file_export_hub_id_376b0c_idx"),
                ],
            },
        ),
    ]
