from django import forms

from credit_institution.models import CreditInstitutionHub
from credit_institution.models import CreditInstitutionStaticSatellite
from baseclasses.repositories.db_helper import select_satellite

