# Generated by Django 4.2 on 2023-07-07 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditInstitutionHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(default="", max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditInstitutionStaticSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credit_institution_name",
                    models.CharField(default="NoName", max_length=255),
                ),
                (
                    "account_upload_method",
                    models.CharField(
                        choices=[("none", "None"), ("dkb", "Dkb")],
                        default="none",
                        max_length=5,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credit_institution.creditinstitutionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
