# Generated by Django 4.2 on 2023-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinstitutionhub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
