# Generated by Django 4.2 on 2023-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_institution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditinstitutionstaticsatellite",
            name="credit_institution_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
