# Generated by Django 4.2 on 2023-12-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinstitutionhub',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='creditinstitutionhub',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='creditinstitutionstaticsatellite',
            name='account_upload_method',
            field=models.CharField(choices=[('none', 'None'), ('dkb', 'Dkb'), ('onvis', 'Onvista'), ('trrep', 'Trade Republic')], default='none', max_length=5),
        ),
    ]
