# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0002_creditinstitutionhub_state_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinstitutionhub',
            name='is_deleted',
        ),
    ]
