# Generated by Django 4.2 on 2023-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "credit_institution",
            "0002_creditinstitutionstaticsatellite_credit_institution_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditinstitutionstaticsatellite",
            name="credit_institution_name",
            field=models.CharField(default="NoName", max_length=255),
        ),
    ]
