# Generated by Django 4.2 on 2023-11-26 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadFileHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadRegistryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('link_file_upload_registry_file_upload_file', models.ManyToManyField(related_name='link_file_upload_file_file_upload_registry', to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadRegistryStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'Csv'), ('json', 'Json'), ('xml', 'Xml'), ('xlsx', 'Xlsx'), ('xls', 'Xls'), ('txt', 'Txt'), ('none', 'None')], default='none', max_length=5)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_message', models.CharField(default='', max_length=255)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadregistryhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadFileStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('file', models.FileField(upload_to='uploads/')),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='fileuploadregistrystaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='file_upload_hash_id_a11d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadregistrystaticsatellite',
            index=models.Index(fields=['hash_value'], name='file_upload_hash_va_851793_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadfilestaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='file_upload_hash_id_9f5938_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadfilestaticsatellite',
            index=models.Index(fields=['hash_value'], name='file_upload_hash_va_5ab0f4_idx'),
        ),
    ]
