# Generated by Django 4.2 on 2023-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadregistryhub",
            name="link_file_upload_registry_file_upload_file",
            field=models.ManyToManyField(
                related_name="link_file_upload_file_file_upload_registry",
                to="file_upload.fileuploadfilehub",
            ),
        ),
    ]
