# Generated by Django 4.2 on 2024-03-29 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadregistrystaticsatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuploadregistrystaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadregistryhub'),
        ),
        migrations.AddField(
            model_name='fileuploadregistryhub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuploadregistryhub',
            name='link_file_upload_registry_file_upload_file',
            field=models.ManyToManyField(related_name='link_file_upload_file_file_upload_registry', through='file_upload.LinkFileUploadRegistryFileUploadFile', to='file_upload.fileuploadfilehub'),
        ),
        migrations.AddField(
            model_name='fileuploadfilestaticsatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuploadfilestaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub'),
        ),
        migrations.AddField(
            model_name='fileuploadfilehub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileuploadregistrystaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='file_upload_hash_id_a11d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadregistrystaticsatellite',
            index=models.Index(fields=['hash_value'], name='file_upload_hash_va_851793_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadfilestaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='file_upload_hash_id_9f5938_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadfilestaticsatellite',
            index=models.Index(fields=['hash_value'], name='file_upload_hash_va_5ab0f4_idx'),
        ),
    ]
