# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadfilehub',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='fileuploadregistryhub',
            name='is_deleted',
        ),
    ]
