# Generated by Django 4.2 on 2024-03-29 20:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldMapStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('source_field', models.CharField(max_length=255, unique=True)),
                ('database_field', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fieldmaphub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='fieldmapstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='file_upload_hash_id_3b8e08_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldmapstaticsatellite',
            index=models.Index(fields=['hash_value'], name='file_upload_hash_va_f01138_idx'),
        ),
    ]
