# Generated by Django 4.2 on 2023-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_fileuploadregistryhub_link_file_upload_registry_file_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadfilehub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileuploadregistryhub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
