# Generated by Django 4.2 on 2024-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0003_fieldmaphub_fieldmapstaticsatellite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapstaticsatellite",
            name="function_name",
            field=models.CharField(default="fn_no_change", max_length=255),
        ),
    ]
