# Generated by Django 4.2 on 2023-11-05 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_fileuploadfilehub_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadfilestaticsatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fileuploadfilestaticsatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fileuploadregistrystaticsatellite',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fileuploadregistrystaticsatellite',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
