# Generated by Django 4.2 on 2024-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_fileuploadfilehub_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadfilestaticsatellite',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
