# Generated by Django 4.2 on 2024-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0004_fieldmapstaticsatellite_function_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldmapstaticsatellite",
            name="source_field",
            field=models.CharField(max_length=255),
        ),
    ]
