# Generated by Django 4.2 on 2024-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0004_alter_fileuploadfilestaticsatellite_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadfilestaticsatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fileuploadregistrystaticsatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
