# Generated by Django 4.2 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0005_fileuploadfilestaticsatellite_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadfilehub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fileuploadregistryhub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="linkfileuploadregistryfileuploadfile",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="fileuploadfilestaticsatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="fileuploadregistrystaticsatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
