# Generated by Django 4.2 on 2024-04-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0005_alter_fieldmapstaticsatellite_source_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapstaticsatellite",
            name="function_parameters",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
