# Generated by Django 4.2 on 2024-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0006_fieldmapstaticsatellite_function_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldmapstaticsatellite",
            name="function_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
