# Generated by Django 4.2 on 2024-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0007_fieldmaphub_alter_fileuploadfilehub_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldmapstaticsatellite",
            name="source_field",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
