# Generated by Django 5.0.4 on 2024-05-26 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_upload", "0007_alter_fieldmapstaticsatellite_function_parameters"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fileuploadregistrystaticsatellite",
            name="file_upload_hash_id_a11d5e_idx",
        ),
        migrations.RemoveIndex(
            model_name="fileuploadregistrystaticsatellite",
            name="file_upload_hash_va_851793_idx",
        ),
    ]
