# Generated by Django 5.0.4 on 2024-05-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_alter_fieldmapstaticsatellite_function_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadregistryhub',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fileuploadregistryhub',
            name='link_file_upload_registry_file_upload_file',
        ),
        migrations.RemoveField(
            model_name='linkfileuploadregistryfileuploadfile',
            name='hub_in',
        ),
        migrations.RemoveField(
            model_name='fileuploadregistrystaticsatellite',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='fileuploadregistrystaticsatellite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='linkfileuploadregistryfileuploadfile',
            name='hub_out',
        ),
    ]
