# Generated by Django 5.0.4 on 2024-05-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_upload",
            "0008_remove_fileuploadregistrystaticsatellite_file_upload_hash_id_a11d5e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fieldmapstaticsatellite",
            name="file_upload_hash_id_3b8e08_idx",
        ),
        migrations.RemoveIndex(
            model_name="fieldmapstaticsatellite",
            name="file_upload_hash_va_f01138_idx",
        ),
    ]
