# Generated by Django 5.0.4 on 2024-05-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountfileuploadregistryhub_and_more'),
        ('company', '0010_bbgcategoricalfileuploadregistryhub_and_more'),
        ('effec_poc', '0043_remove_bondpochub_link_bond_poc_file_upload_registry_and_more'),
        ('file_upload', '0008_remove_fileuploadregistryhub_created_by_and_more'),
        ('montrek_example', '0009_fileuploadregistryhub_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUploadRegistryHub',
        ),
        migrations.DeleteModel(
            name='FileUploadRegistryStaticSatellite',
        ),
        migrations.DeleteModel(
            name='LinkFileUploadRegistryFileUploadFile',
        ),
    ]
