# Generated by Django 5.0.4 on 2024-06-21 06:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0009_remove_fieldmapstaticsatellite_file_upload_hash_id_3b8e08_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFileUploadRegistryLogExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadregistryhub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fileuploadregistryhub',
            name='link_file_upload_registry_log_excel_file',
            field=models.ManyToManyField(related_name='link_log_excel_file_file_upload_registry', through='file_upload.LinkFileUploadRegistryLogExcelFile', to='file_upload.fileuploadfilehub'),
        ),
    ]
