# Generated by Django 5.0.4 on 2024-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_linkfileuploadregistrylogexcelfile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkFileUploadRegistryLogExcelFile',
            new_name='LinkFileUploadRegistryLogFile',
        ),
        migrations.RemoveField(
            model_name='fileuploadregistryhub',
            name='link_file_upload_registry_log_excel_file',
        ),
        migrations.AddField(
            model_name='fileuploadregistryhub',
            name='link_file_upload_registry_log_file',
            field=models.ManyToManyField(related_name='link_log_file_file_upload_registry', through='file_upload.LinkFileUploadRegistryLogFile', to='file_upload.fileuploadfilehub'),
        ),
    ]
