# Generated by Django 5.0.4 on 2024-05-25 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_fileuploadregistryhub_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fileuploadregistrystaticsatellite',
            name='file_upload_hash_id_a11d5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileuploadregistrystaticsatellite',
            name='file_upload_hash_va_851793_idx',
        ),
        migrations.AddField(
            model_name='fileuploadregistrystaticsatellite',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuploadregistrystaticsatellite',
            name='file_type',
            field=models.CharField(choices=[('csv', 'Csv'), ('json', 'Json'), ('xml', 'Xml'), ('xlsx', 'Xlsx'), ('xls', 'Xls'), ('txt', 'Txt'), ('none', 'None')], default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='fileuploadregistrystaticsatellite',
            name='upload_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fileuploadregistrystaticsatellite',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('in_progress', 'In Progress'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
