# Generated by Django 5.0.4 on 2024-06-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0011_rename_linkfileuploadregistrylogexcelfile_linkfileuploadregistrylogfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploadregistryhub',
            old_name='link_file_upload_registry_log_file',
            new_name='link_file_upload_registry_file_log_file',
        ),
    ]
