# Generated by Django 5.0.4 on 2024-06-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0012_rename_link_file_upload_registry_log_file_fileuploadregistryhub_link_file_upload_registry_file_log_f'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkFileUploadRegistryLogFile',
            new_name='LinkFileUploadRegistryFileLogFile',
        ),
    ]
