# Generated by Django 5.0.4 on 2024-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_upload",
            "0013_rename_linkfileuploadregistrylogfile_linkfileuploadregistryfilelogfile",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapstaticsatellite",
            name="step",
            field=models.IntegerField(default=1),
        ),
    ]
