# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more",
        ),
        (
            "file_upload",
            "0015_fieldmaphubvaluedate_fileuploadfilehubvaluedate_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fieldmaphubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="file_upload_value_d_063842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldmaphubvaluedate",
            index=models.Index(fields=["hub"], name="file_upload_hub_id_78b690_idx"),
        ),
        migrations.AddIndex(
            model_name="fileuploadfilehubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="file_upload_value_d_dd873c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadfilehubvaluedate",
            index=models.Index(fields=["hub"], name="file_upload_hub_id_1d7588_idx"),
        ),
        migrations.AddIndex(
            model_name="fileuploadfilestaticsatellite",
            index=models.Index(
                fields=["hub_entity"], name="file_upload_hub_ent_51c421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadregistryhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="file_upload_value_d_abc2a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadregistryhubvaluedate",
            index=models.Index(fields=["hub"], name="file_upload_hub_id_05b23a_idx"),
        ),
    ]
