# Generated by Django 5.1.5 on 2025-05-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_upload",
            "0016_fieldmaphubvaluedate_file_upload_value_d_063842_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadregistrystaticsatellite",
            name="celery_task_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="fileuploadregistrystaticsatellite",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploaded", "Uploaded"),
                    ("in_progress", "In Progress"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
