# Generated by Django 5.2.9 on 2026-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_upload",
            "0017_fileuploadregistrystaticsatellite_celery_task_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileuploadregistrystaticsatellite",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("csv", "Csv"),
                    ("json", "Json"),
                    ("xml", "Xml"),
                    ("xlsx", "Xlsx"),
                    ("xls", "Xls"),
                    ("txt", "Txt"),
                    ("toml", "Toml"),
                    ("none", "None"),
                ],
                default="none",
                max_length=5,
            ),
        ),
    ]
