# Generated by Django 5.2.9 on 2026-10-07 04:35

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sftp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sftpcredentialsatellite",
            name="password",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sftpcredentialsatellite",
            name="private_key",
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sftpcredentialsatellite",
            name="private_key_passphrase",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
