# Generated by Django 5.2.9 on 2026-10-07 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sftp", "0002_sftp_credential_secrets_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sftpconnectionsatellite",
            name="host_key_fingerprint",
            field=models.CharField(
                help_text="SHA256 fingerprint of the server's host key, e.g. 'SHA256:abc…'. Get it from the server's operator, or verify the output of 'ssh-keyscan -p <port> <host> | ssh-keygen -lf -' with them.",
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(SHA256:)?[A-Za-z0-9+/]{43}=?$",
                        "Enter the SHA256 fingerprint of the host key, e.g. 'SHA256:abc…'.",
                    )
                ],
            ),
        ),
    ]
