# Generated by Django 5.2.9 on 2026-10-07 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sftp", "0003_sftp_host_key_fingerprint_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpconnectionsatellite",
            name="trusted_host",
            field=models.BooleanField(
                default=False,
                help_text="Connect without a host key fingerprint. Only for test servers: anyone who can intercept the connection can then pose as the server and receive the credentials.",
            ),
        ),
        migrations.AlterField(
            model_name="sftpconnectionsatellite",
            name="host_key_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 fingerprint of the server's host key, e.g. 'SHA256:abc…'. Get it from the server's operator, or verify the output of 'ssh-keyscan -p <port> <host> | ssh-keygen -lf -' with them.",
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(SHA256:)?[A-Za-z0-9+/]{43}=?$",
                        "Enter the SHA256 fingerprint of the host key, e.g. 'SHA256:abc…'.",
                    )
                ],
            ),
        ),
    ]
