# Generated by Django 5.2.9 on 2026-10-08 09:38

import baseclasses.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0028_delete_mockmodel"),
        ("sftp", "0004_sftp_trusted_host"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkSftpImportSourceSftpConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sftp.sftpconnectionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SftpImportedFileHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("identifier", models.CharField(default="", max_length=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkSftpImportedFileSftpImportSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sftp.sftpimportedfilehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SftpImportSourceHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("identifier", models.CharField(default="", max_length=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link_sftp_import_source_sftp_connection",
                    models.ManyToManyField(
                        related_name="link_sftp_connection_sftp_import_source",
                        through="sftp.LinkSftpImportSourceSftpConnection",
                        to="sftp.sftpconnectionhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sftpimportedfilehub",
            name="link_sftp_imported_file_sftp_import_source",
            field=models.ManyToManyField(
                related_name="link_sftp_import_source_sftp_imported_file",
                through="sftp.LinkSftpImportedFileSftpImportSource",
                to="sftp.sftpimportsourcehub",
            ),
        ),
        migrations.AddField(
            model_name="linksftpimportsourcesftpconnection",
            name="hub_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sftp.sftpimportsourcehub",
            ),
        ),
        migrations.AddField(
            model_name="linksftpimportedfilesftpimportsource",
            name="hub_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sftp.sftpimportsourcehub",
            ),
        ),
        migrations.CreateModel(
            name="SftpImportedFileHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="sftp.sftpimportedfilehub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["value_date_list"],
                        name="sftp_sftpim_value_d_4d434b_idx",
                    ),
                    models.Index(fields=["hub"], name="sftp_sftpim_hub_id_3d3bb4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SftpImportedFileSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("import_key", models.CharField(db_index=True, max_length=1300)),
                ("remote_path", models.CharField(max_length=1024)),
                ("file_size", models.BigIntegerField()),
                ("file_modified", models.DateTimeField(blank=True, null=True)),
                ("upload_type", models.CharField(max_length=255)),
                ("registry_hub_id", models.BigIntegerField(blank=True, null=True)),
                ("import_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sftp.sftpimportedfilehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["hash_identifier"],
                        name="sftp_sftpim_hash_id_8ae968_idx",
                    ),
                    models.Index(
                        fields=["hash_value"], name="sftp_sftpim_hash_va_3e50d5_idx"
                    ),
                    models.Index(
                        fields=["hub_entity"], name="sftp_sftpim_hub_ent_5a461d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SftpImportSourceHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    baseclasses.fields.HubForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="sftp.sftpimportsourcehub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["value_date_list"],
                        name="sftp_sftpim_value_d_13dc72_idx",
                    ),
                    models.Index(fields=["hub"], name="sftp_sftpim_hub_id_be8717_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SftpImportSourceSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "remote_dir",
                    models.CharField(
                        default=".",
                        help_text="Directory to poll, relative to the connection's base path.",
                        max_length=1024,
                    ),
                ),
                (
                    "file_pattern",
                    models.CharField(
                        default="*",
                        help_text="Only files matching this glob are imported, e.g. '*.csv'.",
                        max_length=255,
                    ),
                ),
                ("upload_type", models.CharField(max_length=255)),
                (
                    "pipeline_parameters",
                    models.JSONField(
                        blank=True,
                        help_text='What the pipeline would otherwise get from the upload form, e.g. {"overwrite": false}.',
                        null=True,
                    ),
                ),
                (
                    "min_file_age_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Files modified more recently are skipped, as they may still be being written.",
                    ),
                ),
                (
                    "processed_dir",
                    models.CharField(
                        blank=True,
                        default="processed",
                        help_text="Imported files are moved here, relative to the polled directory. Leave empty to keep them in place.",
                        max_length=1024,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active sources are polled on schedule.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sftp.sftpimportsourcehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["hash_identifier"],
                        name="sftp_sftpim_hash_id_e48dd4_idx",
                    ),
                    models.Index(
                        fields=["hash_value"], name="sftp_sftpim_hash_va_97e166_idx"
                    ),
                    models.Index(
                        fields=["hub_entity"], name="sftp_sftpim_hub_ent_b5befa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SftpImportSourceStatusSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_poll_status",
                    models.CharField(
                        choices=[
                            ("never", "Never polled"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("last_poll_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sftp.sftpimportsourcehub",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["hash_identifier"],
                        name="sftp_sftpim_hash_id_9d2d04_idx",
                    ),
                    models.Index(
                        fields=["hash_value"], name="sftp_sftpim_hash_va_5ec572_idx"
                    ),
                    models.Index(
                        fields=["hub_entity"], name="sftp_sftpim_hub_ent_5811b7_idx"
                    ),
                ],
            },
        ),
    ]
