# Generated by Django 4.2 on 2023-05-09 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMontrekHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMontrekSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0))),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testmontrekhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMontrekLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_hub', to='baseclasses.testmontrekhub')),
                ('to_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_hub', to='baseclasses.testmontrekhub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
