# Generated by Django 4.2 on 2023-11-26 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLinkHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMontrekHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMontrekSatelliteNoIdFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testmontrekhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMontrekSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('test_name', models.CharField(max_length=12)),
                ('test_value', models.CharField(default='DEFAULT', max_length=50)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testmontrekhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestLinkSatelitte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('test_id', models.IntegerField(default=0)),
                ('hub_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testlinkhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testlinkhub',
            name='test_hub',
            field=models.ManyToManyField(related_name='test_link_hub', to='baseclasses.testmontrekhub'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellitenoidfields',
            index=models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_3f5cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellitenoidfields',
            index=models.Index(fields=['hash_value'], name='baseclasses_hash_va_72cf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellite',
            index=models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_f98374_idx'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellite',
            index=models.Index(fields=['hash_value'], name='baseclasses_hash_va_b2d38b_idx'),
        ),
        migrations.AddIndex(
            model_name='testlinksatelitte',
            index=models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_3eee04_idx'),
        ),
        migrations.AddIndex(
            model_name='testlinksatelitte',
            index=models.Index(fields=['hash_value'], name='baseclasses_hash_va_653fb5_idx'),
        ),
    ]
