# Generated by Django 4.2 on 2024-03-29 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseclasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testmontreksatellitenoidfields',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmontreksatellitenoidfields',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testmontrekhub'),
        ),
        migrations.AddField(
            model_name='testmontreksatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmontreksatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testmontrekhub'),
        ),
        migrations.AddField(
            model_name='testmontrekhub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testlinksatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testlinksatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testlinkhub'),
        ),
        migrations.AddField(
            model_name='testlinkhub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testlinkhub',
            name='link_link_hub_test_montrek_hub',
            field=models.ManyToManyField(related_name='link_test_montrek_hub_link_hub', through='baseclasses.LinkTestMontrekTestLink', to='baseclasses.testmontrekhub'),
        ),
        migrations.AddField(
            model_name='linktestmontrektestlink',
            name='hub_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testmontrekhub'),
        ),
        migrations.AddField(
            model_name='linktestmontrektestlink',
            name='hub_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testlinkhub'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellitenoidfields',
            index=models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_3f5cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellitenoidfields',
            index=models.Index(fields=['hash_value'], name='baseclasses_hash_va_72cf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellite',
            index=models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_f98374_idx'),
        ),
        migrations.AddIndex(
            model_name='testmontreksatellite',
            index=models.Index(fields=['hash_value'], name='baseclasses_hash_va_b2d38b_idx'),
        ),
        migrations.AddIndex(
            model_name='testlinksatellite',
            index=models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_4972f4_idx'),
        ),
        migrations.AddIndex(
            model_name='testlinksatellite',
            index=models.Index(fields=['hash_value'], name='baseclasses_hash_va_0df77e_idx'),
        ),
    ]
