# Generated by Django 4.2 on 2023-12-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestLinkSatelitte',
            new_name='TestLinkSatellite',
        ),
        migrations.RenameIndex(
            model_name='testlinksatellite',
            new_name='baseclasses_hash_id_4972f4_idx',
            old_name='baseclasses_hash_id_3eee04_idx',
        ),
        migrations.RenameIndex(
            model_name='testlinksatellite',
            new_name='baseclasses_hash_va_0df77e_idx',
            old_name='baseclasses_hash_va_653fb5_idx',
        ),
        migrations.RemoveField(
            model_name='testlinkhub',
            name='test_hub',
        ),
        migrations.AddField(
            model_name='testlinkhub',
            name='link_link_hub_test_montrek_hub',
            field=models.ManyToManyField(related_name='link_test_montrek_hub_link_hub', to='baseclasses.testmontrekhub'),
        ),
    ]
