# Generated by Django 4.2 on 2023-05-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmontreksatellite',
            name='test_name',
            field=models.CharField(default='Bla', max_length=12),
            preserve_default=False,
        ),
    ]
