# Generated by Django 4.2 on 2023-12-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkhubahubb',
            name='hub_in',
        ),
        migrations.RemoveField(
            model_name='linkhubahubb',
            name='hub_out',
        ),
        migrations.RemoveField(
            model_name='linkhubahubc',
            name='hub_in',
        ),
        migrations.RemoveField(
            model_name='linkhubahubc',
            name='hub_out',
        ),
        migrations.RemoveField(
            model_name='sata1',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='sata2',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='satb1',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='satb2',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='satc1',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='sattsc2',
            name='hub_entity',
        ),
        migrations.AddField(
            model_name='testlinkhub',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='testlinkhub',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='testmontrekhub',
            name='state_date_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='testmontrekhub',
            name='state_date_start',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='HubA',
        ),
        migrations.DeleteModel(
            name='HubB',
        ),
        migrations.DeleteModel(
            name='HubC',
        ),
        migrations.DeleteModel(
            name='LinkHubAHubB',
        ),
        migrations.DeleteModel(
            name='LinkHubAHubC',
        ),
        migrations.DeleteModel(
            name='SatA1',
        ),
        migrations.DeleteModel(
            name='SatA2',
        ),
        migrations.DeleteModel(
            name='SatB1',
        ),
        migrations.DeleteModel(
            name='SatB2',
        ),
        migrations.DeleteModel(
            name='SatC1',
        ),
        migrations.DeleteModel(
            name='SatTSC2',
        ),
    ]
