# Generated by Django 4.2 on 2023-08-09 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestLinkHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(default="", max_length=12)),
                ("test_hub", models.ManyToManyField(to="baseclasses.testmontrekhub")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestLinkSatelitte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hash_identifier", models.CharField(default="", max_length=64)),
                ("hash_value", models.CharField(default="", max_length=64)),
                (
                    "state_date_start",
                    models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
                    ),
                ),
                ("test_id", models.IntegerField(default=0)),
                (
                    "hub_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.testlinkhub",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="TestMontrekLink",
        ),
        migrations.AddIndex(
            model_name="testlinksatelitte",
            index=models.Index(
                fields=["hash_identifier"], name="baseclasses_hash_id_3eee04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testlinksatelitte",
            index=models.Index(
                fields=["hash_value"], name="baseclasses_hash_va_653fb5_idx"
            ),
        ),
    ]
