# Generated by Django 4.2 on 2024-02-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmontreksatellite',
            name='test_decimal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
