# Generated by Django 4.2 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0002_remove_linkhubahubb_hub_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlinkhub',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testmontrekhub',
            name='is_deleted',
        ),
    ]
