# Generated by Django 4.2 on 2023-08-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0002_testlinkhub_testlinksatelitte_delete_testmontreklink_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testlinkhub",
            name="test_hub",
            field=models.ManyToManyField(
                related_name="test_link_hub", to="baseclasses.testmontrekhub"
            ),
        ),
    ]
