# Generated by Django 5.0.4 on 2024-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueDateList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_date", models.DateField(unique=True)),
            ],
        ),
    ]
