# Generated by Django 4.2 on 2024-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseclasses",
            "0003_testlinkhub_created_by_testlinksatellite_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testlinksatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testmontreksatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testmontreksatellitenoidfields",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
