# Generated by Django 4.2 on 2023-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0003_alter_testlinkhub_test_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlinkhub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testmontrekhub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
