# Generated by Django 5.0.4 on 2024-11-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0003_valuedatelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestHubValueDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_value_date",
                        to="baseclasses.testmontrekhub",
                    ),
                ),
                (
                    "value_date_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baseclasses.valuedatelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
