# Generated by Django 4.2 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0004_testlinksatellite_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linktestmontrektestlink",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testlinkhub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testmontrekhub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="testlinksatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="testmontreksatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="testmontreksatellitenoidfields",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
