# Generated by Django 5.0.4 on 2024-11-14 12:49

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0004_testhubvaluedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testhubvaluedate",
            name="hub",
            field=baseclasses.fields.HubForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_value_date",
                to="baseclasses.testmontrekhub",
            ),
        ),
    ]
