# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0005_alter_testhubvaluedate_hub"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testhubvaluedate",
            index=models.Index(
                fields=["value_date_list"], name="baseclasses_value_d_976969_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testhubvaluedate",
            index=models.Index(fields=["hub"], name="baseclasses_hub_id_b0e925_idx"),
        ),
        migrations.AddIndex(
            model_name="testlinksatellite",
            index=models.Index(
                fields=["hub_entity"], name="baseclasses_hub_ent_19c945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmontreksatellite",
            index=models.Index(
                fields=["hub_entity"], name="baseclasses_hub_ent_02c9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmontreksatellitenoidfields",
            index=models.Index(
                fields=["hub_entity"], name="baseclasses_hub_ent_12c626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valuedatelist",
            index=models.Index(
                fields=["value_date"], name="baseclasses_value_d_fad0fe_idx"
            ),
        ),
    ]
