# Generated by Django 5.1.5 on 2025-02-06 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmontreksatellite',
            name='test_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
