# Generated by Django 5.1.5 on 2025-02-06 12:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0007_testmontreksatellite_test_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMontrekTimeSeriesSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('test_decimal', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('hub_value_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.testhubvaluedate')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['hash_identifier'], name='baseclasses_hash_id_d6c4cb_idx'), models.Index(fields=['hash_value'], name='baseclasses_hash_va_2c653c_idx'), models.Index(fields=['hub_value_date'], name='baseclasses_hub_val_649d90_idx')],
            },
        ),
    ]
