# Generated by Django 5.1.5 on 2025-05-14 09:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0008_testmontrektimeseriessatellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubARepositoryViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_a1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_a1_int', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('field_a2_str', models.CharField(blank=True, default='DEFAULT', max_length=50, null=True)),
                ('field_a2_float', models.FloatField(blank=True, default=0.0, null=True)),
                ('field_b1_str', models.CharField(default='DEFAULT', max_length=50)),
                ('field_b1_date', models.DateField(default=django.utils.timezone.now)),
                ('value_date', models.DateTimeField()),
                ('hub_entity_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.EmailField(max_length=254)),
                ('comment', models.CharField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
