# Generated by Django 5.1.5 on 2025-06-18 04:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0008_testmontrektimeseriessatellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyLinkClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_hub', to='baseclasses.montrekhubabc')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_hub', to='baseclasses.montrekhubabc')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['hub_in'], name='baseclasses_hub_in__96de6e_idx'), models.Index(fields=['hub_out'], name='baseclasses_hub_out_ad23be_idx')],
            },
        ),
    ]
