# Generated by Django 5.1.5 on 2025-06-19 06:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0008_testmontrektimeseriessatellite"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyLinkClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_date_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "state_date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
