# Generated by Django 5.1.5 on 2025-06-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0009_dummylinkclass"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyLinkClass",
        ),
    ]
