# Generated by Django 5.1.5 on 2025-05-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0009_hubarepositoryviewmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HubARepositoryViewModel",
        ),
    ]
