# Generated by Django 5.1.5 on 2025-05-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0011_hubarepositoryviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HubARepositoryViewModel',
        ),
    ]
