# Generated by Django 5.1.5 on 2025-07-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0011_dummylinkclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyLinkClass',
        ),
    ]
