# Generated by Django 5.1.5 on 2025-05-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0013_hubarepositoryviewmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hubarepositoryviewmodel',
            table='hubarepository_view_model',
        ),
    ]
