# Generated by Django 5.1.5 on 2025-08-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0013_dummylinkclass"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyLinkClass",
        ),
    ]
