# Generated by Django 5.1.5 on 2025-05-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0014_alter_hubarepositoryviewmodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HubARepositoryViewModel',
        ),
    ]
