# Generated by Django 5.1.5 on 2025-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0014_delete_dummylinkclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmontreksatellite",
            name="test_text",
            field=models.TextField(null=True),
        ),
    ]
