# Generated by Django 5.1.5 on 2025-10-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0015_testmontreksatellite_test_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmontreksatellite",
            name="test_text",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
