# Generated by Django 5.1.5 on 2025-10-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0017_mockmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockModel",
        ),
    ]
