# Generated by Django 5.1.5 on 2025-11-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0019_mockmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockModel",
        ),
    ]
