# Generated by Django 5.1.5 on 2025-11-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0021_mockmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockModel",
        ),
    ]
