# Generated by Django 5.1.5 on 2025-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0022_delete_mockmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
