# Generated by Django 5.2.9 on 2025-12-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0023_mockmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockModel",
        ),
    ]
