# Generated by Django 5.2.9 on 2026-02-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0025_mockmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockModel",
        ),
    ]
