# Generated by Django 5.2.9 on 2026-02-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0027_mockmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockModel",
        ),
    ]
