# Generated by Django 5.2.9 on 2026-10-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseclasses", "0028_delete_mockmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testlinksatellite",
            name="hub_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_link_satellites",
                to="baseclasses.testlinkhub",
            ),
        ),
    ]
